### ISSUE TITLE
Add half hour timezone support

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#10060]
Right now, we store an integer hour offset, but also timezones in another field. Some countries have a timezone that is half an hour from UTC. Right now they are not supported due to us using the integer offset.

We should see if we can use our string timezone rather than the hour offset for time calculations.

See also: https://github.com/vanilla/support/issues/1143

**Comment by ElizeRowe** [comment]
Just as a note, one of Oracle's users has also reported this (https://vanilla.freshdesk.com/a/tickets/84129). I advised CSM that the issue is open still and will be dealt with in due course.

_"I've got one India-based user of My Oracle Support Community (Srini-S) who is reporting that when he creates a new post, the timestamp that displays is always 30 minutes behind the actual time. For example, he creates a question at 12.10 PM local time and the post immediately shows as 11.40AM.

He tells me that his current time zone is GMT+5.30 (i.e., IST).

From all I have been able to research, Vanilla Forums doesn't require users to specify a timezone in their individual profiles; that information is grabbed from the user's local device. Am I correct about that? And if so (or even if not), is there any explanation why the system time on the community post would be off by that half hour? He is unable to tell me what timezone his device is presently set to, but he states that no other application shows this time discrepancy. Thoughts?"_
