### ISSUE TITLE
Question about that stale bot

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#10147]
I see more and more issues getting closed because no one reacted on them. Is it my/the issue creators duty to keep such issues open?

Call me stubborn or oldfashioned, but I'm not willing to tell a bot that a problem still persists. If I bring something up, I feel like my job has been done.

It's up to you to judge if an issue will get a "won't fix" label and do not work on such an issue, which is absolutely okay for me. But just because a problem hasn't solved or no one feels responsible for it, it doesn't stop being a problem...

**Comment by charrondev** [comment]
@R-J We've been looking at it that someone can't bother to make any activity on an issue when notified by the bot that the issue will be closed (that's all that's required. ___any activity___), then the issue obviously wasn't that important.

Vanilla is an old product. We churn through thousands of issues, just on this repo, and 1000s on our other private ones every year, with a dev team of ~10 people.

This is helping us immensely to prioritize our backlog. If you see the priority order of how we go through issues it may make more sense.

## Priority

1. Critical/High severity security issues.
2. Critical/High priority customer tickets (those live in another repo).
3. ~80% Ongoing roadmap goals & ~20% other customer tickets.
4. Technical debt issues opened by our team members from previous roadmap items.
5. Everything else.

The thing is, most issues filed on this repo, even by our own team members, falls under everything else, and we essentially never get there. On top of that many of these "everything" else issues fall into our legacy Gdn_Controllers and views, or our loosely typed legacy event system. Most of the time that we fix a bug there, another one springs up due to lack of a solid foundation and test coverage.

One of the big ongoing roadmap projects has been.

- Build a compatibility layer between the new theme system we use in react/api-driven controllers and the old Gdn_Controllers and views. (almost complete).
- Start rebuilding pages 1 at a time using this compatibility layer.

When rebuilding these pages, any existing bugs related to:

- Data inconsistency.
- UI issues.

Will no longer be valid, and we should have less spring up in the transition (due to automated test coverage, and much stronger primitives to build on).

## Closed issues

All it takes to "save" an issue is to leave any comment on the issue. It could just be "Still relevant" or "I still care about this".

Some issues like this one https://github.com/vanilla/vanilla/issues/8446 are still relevant, but we let it get closed out because we completely new navigation menu (already released to vanilla cloud). Right now you can[ see it on our success KB](https://success.vanillaforums.com/kb/articles/182-release-2020-003), but it will become the default in the next release or 2.

**Comment by charrondev** [comment]
For reference this my teams project board. Most issues being closed are essentially a "won't fix" because our product backlog gets filled up almost as fast is it gets cleared out, and the stuff in the icebox we'll only get to in the next 3 years if:

- It gets a sudden priority bump. In cases like this, acceptance criteria for completion of the issue often changes too though, so we tend to open a new issue.
- We triple our team velocity.
- We stop gaining new customers and our product backlog dries up.

<img width="445" alt="Screen Shot 2020-03-02 at 9 59 17 AM" src="https://user-images.githubusercontent.com/1770056/75687952-9be63480-5c6c-11ea-9ca9-ea423ed61d8e.png">
