### ISSUE TITLE
Foundation: Social Groups styling issues 

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10437]
When on the Groups page, the boxes that contain different modules like 'my groups, new groups, popular groups are a little off:

![Screen Shot 2020-04-15 at 8 41 34 AM](https://user-images.githubusercontent.com/24961134/79351599-dd722c80-7f06-11ea-9350-1b9bb8baff09.png)

**Comment by Bparm** [comment]
Also on the member list in the group:
![Screen Shot 2020-04-15 at 2 33 32 PM](https://user-images.githubusercontent.com/24961134/79375329-72385280-7f26-11ea-8803-c9a6a418409f.png)

**Comment by vrjrobitaille** [comment]
This has improved since it was reported. We also have issues in the backlog for redesigning these pages. we do not know yet when this will be doable, but mockups and estimates are completed. I'm hoping we'll get to this in the fall. We'll keep you updated. 

![Screen Shot 2020-07-06 at 4 49 44 PM](https://user-images.githubusercontent.com/18470831/86641319-0c99b680-bfa9-11ea-9e87-ab9559f0c335.png)

![Screen Shot 2020-07-06 at 4 51 20 PM](https://user-images.githubusercontent.com/18470831/86641349-13282e00-bfa9-11ea-9cb5-9e2be54f9e82.png)
