### ISSUE TITLE
Smarty Security: not trusted file path

### ISSUE THREAD

**Issue by Dannymx** [vanilla/vanilla#10936]
**Describe the bug**
Did a fresh install of the latest release from the master branch `4.0-2020.015-SNAPSHOT`. All the main pages discussions/categories/dashboard seem to be working fine except when you visit any thread.

ie. going to `https://redacted.test/discussion/1/welcome-to-awesome#latest` throws the following 500 error.
```
PHP Fatal error:  Uncaught  --> Smarty: Smarty Security: not trusted file path 'C:\Users\Danny\Code\redacted\vanilla\plugins\rich-editor\views\rich-editor.tpl'  <-- 
  thrown in C:\Users\Danny\Code\redacted\vanilla\vendor\smarty\smarty\libs\sysplugins\smarty_security.php on line 654
```

**To Reproduce**
1. Fresh install of `4.0-2020.015-SNAPSHOT`
2. Run setup
3. Open any of the sample threads

**Expected behavior**
Open thread without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/364003/91915170-72d84800-ec7f-11ea-8baa-aec23b0e92c0.png)

**Comment by anaggh** [comment]
Can confirm on Build: `vanilla-core-2021-009`

# Reproduce Steps
* Windows 10
* Install XAMPP PHP 7.4 (Enable php-intl in php.ini otherwise your setup will not complete `\Locale::` errors) 
* New Discussion > HTTP 500

<img width="520" alt="http500" src="https://user-images.githubusercontent.com/9278844/118619504-48fd8c00-b7e2-11eb-915b-51da1d6153d8.png">

```
[Web Server ] May 18 13:49:55 |ERROR  | SERVER GET  (500) /index.php?p=/post/discussion
[Web Server ] C:\xampp\htdocs\vanilla\vendor\smarty\smarty\libs\sysplugins\smarty_security.php on line 661
```

Commenting the line fixes it 
```
        // give up
       // throw new SmartyException(sprintf('Smarty Security: not trusted file path \'%s\' ', $filepath));
```

**Comment by TheEternalNoob** [comment]
This issue for me was caused by loading the rich-editor plugin, which was not listed in the trusted dirs of smarty. A solution that worked for me was setting 
`/* $folder_to_plugins is the path to the plugins directory (didn't check if there were any other plugins using this) */
$security->secure_dir =$folder_to_plugins;`

in the enableSecurity function in library/core/class.smarty.php

**Comment by todosrc** [comment]
i have the same issue vanilla-2021012 run localhost@xampp
