### ISSUE TITLE
/categories endpoint pagination doesn't work

### ISSUE THREAD

**Issue by privorka** [vanilla/vanilla#11056]
**Describe the bug**
When using the v2 API GET /categories endpoint, the pagination doesn't seem to work.
Page 1 returns the same data as page 2, etc.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? Yes
2. What Vanilla version are you using? 2021.008 (+ docker using the local setup)

**To Reproduce**
1. Send a GET request to /categories?page=1
2. Change the page query value and try again. (changing the maxDepth or limit doesn't help)

**Comment by charrondev** [comment]
This endpoint changed a fair bit in the 2022 releases (including an `outputFormat=flat` parameter that returns a flat list with support for pagination instead of a nested list.

In the older releases you have to add something like `categoryID=0..10000000` to trigger the flat list and enable pagination support.
