### ISSUE TITLE
"User Profile" settings page blank OSS 2022.025 No UI for Managing Custom Fields

### ISSUE THREAD

**Issue by AltB** [vanilla/vanilla#11170]
Dashboard - > settings -> 'User Profile' render a blank page : no user profile redirection and no profile extended fields (plugin disable).
There's no UI for Managing Custom Fields (and since 2022.025 extended profile fields plugin is removed)

Note :
Since 2022.019 2022.020 2022.021 2022.022 2022.023 2022.024 2022.025 The controller applications/dashboard/controllers/class.settingscontroller.php have public function profile() { } empty. Just permission check, title set and a render !

**Comment by Github-Newbie5432** [comment]
Hi AltB,

I built 2023.001 this morning from source and this seems to be fixed in this release. Have uploaded the release here if you'd like to download (and it works on PHP 8.1.12 + PHP 8.2.1 without any workarounds!)

https://open.vanillaforums.com/discussion/39237/vanilla-2023-001-open-source-release-php-8-works-built-from-source
