### ISSUE TITLE
Registration Confirmation Email Link broken on Subdomain

### ISSUE THREAD

**Issue by gooki** [vanilla/vanilla#1790]
When installed on a subdomain ie. forum.xyz.com

The link to the website in the confirm your email address email is broken.

Example:

You can access the site at http://forum
.xyz.com

It appears that anything past the dot is not linked.

**Comment by alexrm1x** [comment]
Hello all,

I'm also seeing this problem in my site.
Version 2.1.9
I setup vanilla in a subdomain (not sure if it happens with other cases):
http://forum.domain.com

When users receive email for confirmation, the email lines are broken with "=" characters.

This happens if you receive the email to gmail.com or hotmail.com addresses opening the email from a web browser in a computer (mail.google.com or www.hotmail.com).

However, the same email and its confirmation links appear and work OK opening from mobile devices like iPhone Mail app or Mail on Android.

On PC (not the "=" characters at the end of the lines::

Hello Alejandra!

You need to confirm your email address before you can=
continue. Please confirm your email address by clicking on the following l=
ink: http://foro.supermujer.net/index.php?p=/entry/emailconfirm/5/GGDAGJJ=
6

Have a great day!

**Comment by alexrm1x** [comment]
This is the email source in gmail.com (show original function)
In this case, receiving to Gmail, it worked.

Delivered-To: (hidden)
Received: by 10.28.185.146 with SMTP id j140csp686708wmf;
        Sun, 29 Mar 2015 07:53:22 -0700 (PDT)
X-Received: by 10.55.33.193 with SMTP id f62mr59466798qki.1.1427640801712;
        Sun, 29 Mar 2015 07:53:21 -0700 (PDT)
Return-Path: (hidden)
Received: from (hidden) ((hidden). [(hidden)])
        by mx.google.com with ESMTP id f22si7825480qkf.4.2015.03.29.07.53.21
        for <(hidden)>;
        Sun, 29 Mar 2015 07:53:21 -0700 (PDT)
Received-SPF: none (google.com: noreply@(hidden) does not designate permitted sender hosts) client-ip=104.236.245.115;
Authentication-Results: mx.google.com;
       spf=none (google.com: noreply@(hidden) does not designate permitted sender hosts) smtp.mail=noreply@(hidden)
Received: by (hidden) (Postfix, from userid 48)
	id A4DC54231C; Sun, 29 Mar 2015 10:53:20 -0400 (EDT)
To: (hidden)
Subject: =?utf-8?Q?[Supermujer]_Confirma_Tu_Direcci=C3=B3n_de_Email?=
X-PHP-Originating-Script: 0:class.phpmailer.php
Date: Sun, 29 Mar 2015 14:53:20 +0000
From: Supermujer <noreply@(hidden)>
Message-ID: <f2ed8d77bdbd9526378ac89642623697@foro.supermujer.net>
X-Priority: 3
X-Mailer: PHPMailer 5.1 (phpmailer.sourceforge.net)
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset="utf-8"

=C2=A1Hola Catalina!=0A=0ANecesitas confirmar tu direcci=C3=B3n de email an=
tes de poder continuar. Por favor confirma tu direcci=C3=B3n de email dando=
 clic en el siguiente enlace: http://foro.supermujer.net/index.php?p=3D/ent=
ry/emailconfirm/7/W8FCZ76Y=0A=C2=A1Que tengas un buen d=C3=ADa!

**Comment by harishreddy-m** [comment]
I am using vanilla 2.3
Still same problem.

AhalyaOnline http://ahalyaonline.epizy.com/vanilla/=0A=0A=0A=0AWelcome Aboa=
rd!=0A=0A=0A=0AHello asdf! You have successfully registered for an account =
at AhalyaOnline. Find your account information below.=0A=0AUsername:

**Comment by harishreddy-m** [comment]
In library/core/class.email.php
in line 45
change 'quote-printable' to '8bit'

It will solve this problem.

**Comment by DaazKu** [comment]
I tried on master and 2.3 and I could not reproduce.

I tried with `xvy.epizy.com` and `forum.vanilla.dev`. Everything was fine on hotmail, gmail and mailinator.

**Comment by MeVsGOD** [comment]
Please help me , I'm using vanilla forum 3.3 everything working only email and smtp not working.
