### ISSUE TITLE
vBulletin migration misses redirects for OP-as-post

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2383]
Direct-to-post links that are OPs break during migration. vBulletin can reference what we call a "Discussion" as an individual post.

Example: http://icrontic.com/forum/showthread.php?p=4

**Comment by DaazKu** [comment]
This has nothing to do with migration.

The redirection is done in [showthread.php](https://github.com/vanilla/vanilla/blob/287f3fda39a53836db067e579fe18a454e8d995c/showthread.php)

For performance reasons I don't think it would be wide to change this code. We could update the Redirector plugin to take care of that issue though.

**Comment by linc** [comment]
It does, because we're not storing sufficient data for Redirector to do this redirect. Discussions do not store their old PostID currently.

**Comment by DaazKu** [comment]
I'm not sure that I'm following here.

The DiscussionID IS the old PostID. The problem is that we assume that "p" will always be a Comment.

What I propose is to modify showthread.php and add a parameter that state it was redirected.
So instead of 
`http://icrontic.com/forum/showthread.php?p=4` 
being rewritten to
`http://icrontic.com/discussion/comment/4#Comment_4`
it would be rewritten to 
`http://icrontic.com/discussion/comment/4?source=showthread#Comment_4`

And then we can catch the not found exception in the Redirector plugin and check for `source=showthread` and redirect to the discussion instead.

**Comment by DaazKu** [comment]
Does my last comment make sense or not?

**Comment by linc** [comment]
It doesn't, because vBulletin uses IDs fundamentally different than we do.

vBulletin assigns a `thread_id`, but unlike Vanilla, the OP has a separate `post_id`. So the OP actually has TWO ways of being referenced numerically: by thread, or by post. When we import, we are discarding its `post_id` and making its `thread_id` the `DiscussionID`. So now when I point at `p=4` I am actually asking for a DISCUSSION whose OP formerly had the `post_id` of 4.

**Comment by DaazKu** [comment]
We have a problem with this: https://github.com/vanilla/vanilla/blob/master/showthread.php#L15
This capture the request before we can do anything with the redirector plugin.

PHPbb treat `showthread.php?p=5913` as `showpost.php?p=5913` but the correct link is the latter.

**Comment by DaazKu** [comment]
If you are not on our infrastructure which allows only index.php to be called) that file hijack the whole request so the redirector plugin will never work properly.
