### ISSUE TITLE
Plugin swap 2015

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2420]
**Move to Addons:**

* Emotify
* cleditor
* embedvanilla
* Buttons
* Sprites
* Google Sign In

**Move into core:**

* Advanced Editor
* Google Plus
* StopForumSpam
* Quotes
* PrivateCommunity
* IndexPhotos (Discussion Photos) - added per comments
* Vanillicon

Concerns, objections, other ideas?

Suggestions of "Signatures" in core will trigger an ejector seat under your chair.

**Comment by linc** [comment]
I kinda wanna move Button Bar to addons, too. Any opinions on that?

**Comment by bleistivt** [comment]
Neutral about ButtonBar, but if you are moving button bar to addons in favor of the new editor, the same could be done to fileupload too.

How about moving IndexPhotos into the core? I see this enabled on more than ~50% of vanilla forums I know and it gets constantly asked about in the community. Plus its pretty easy to support.

**Comment by linc** [comment]
FileUpload was never in core.

Yay! I totally love IndexPhotos and would be delighted to add it to core.

**Comment by hgtonight** [comment]
My thoughts:

Keep ButtonBar where it is as the "basic" editor.
Move Debugger out of core since it is only of use to devs.
Move SteamConnect into core.
I second moving Spoilers, but it sounds like you plan on refactoring that into core parsing anyway.

**Comment by kaecyra** [comment]
Debugger needs to stay in core. It is default disabled but is part of the toolset needed by people getting started with Vanilla and is a key component of the Vanilla/Garden platform.

**Comment by hgtonight** [comment]
@kaecyra Would you accept a pull request to make Debugger enable debug mode (`$Configuration['Debug'] = TRUE;`)?

My reasoning is that you ask someone to turn on debug mode and they enable the Debugger plugin which doesn't turn on debug mode.

**Comment by kaecyra** [comment]
I would. As long as it turns debug off when it disables, as well.

**Comment by linc** [comment]
I don't think enough people even know what Steam is to warrant going in core. I know it's totally obvious to us gamer developers, but 90% of the world will give you a blank look if you mention it.

**Comment by linc** [comment]
I've filed an issue for Spoilers here: https://github.com/vanilla/vanilla/issues/2426 We don't want the plugin in core, we just want it to *be* core.

**Comment by R-J** [comment]
What is the reason for having a repo Vanilla and a repo Addons? I find it hard to understand why there is that distinction and following this discussion, it is obviously hard for everybody else to draw a line between those repos.  

I know that by design Vanilla is proud to be lean and that a lot of functionality should be added by plugins. But I have the impression that by dividing your repos that way, you make it hard for new users to get a full impression on what Vanilla is capable of.  
   
To me it is a binary question:  
   
1. Either you provide a barebone download with no additional plugins so that it is a) a small package to download and b) obvious that some additional content *has to be downloaded* when the plugin section in the dashboard is empty. A link to the repo would be helpful in this case.    
2. Or every plugin of your company is bundled with Vanilla in one handy download package and a new board owner could concentrate on customizing his new forum (and I guess that is what he wants to do)  and doesn't have to look at his Vanilla/plugins folder, the Vanilla/Addons repo and vf.org/addons.   
    
I guess it is obvious what I would prefer ;)

**Comment by linc** [comment]
Great question @R_J. 

We put addons into core that we feel 80% or more of forums could or should reasonably enable. They are our way of saying "try these; if you turned all of them on at once, you wouldn't be any worse off".

Meanwhile, our Addons repo is the ones where we think "sure, there are legitimate uses for these, but they're worth seeking out if you actually need them". The classic example is Signatures. We universally hate it, but if you need it, fine, there it is. Another is QnA: If that's the type of site you want to run, sweet! We just don't think it'll be very many in the big picture.

If someone asked me to set them up a forum and didn't tell me anything else, the core ones are the ones I would search around the Internet for and gather for them right off the bat. We're saving everyone that energy.

Don't forget: Not everyone is going to be able to find & upload addons as quickly and easily as a developer like you. :) The overhead is pretty big, so I feel like it's well worth it to have a curated collection in core.

**Comment by R-J** [comment]
Seems like I haven't written as intentional as I wanted to or I don't get the irony - blame it on my native language...  :-|   
   
I am deeply convinced that having a one ZIP download for all Vanilla files would be the preferred solution for 

1. admins: they want to configure the board and get started as soon as possible, having as much bells and whistles as possible. The more plugins and themes there are, the better!   
2. developers: download one file and have as many resources as possible.  
3. users: I think it is not really important for them. Maybe one or the other is interested in the capabilities of the software and therefore it would be nice for them to have them at one place, but I do not think that they really count  
4. **Vanilla Inc**: isn't it easier to sync? You always have to take care that you have a master, stage and 2.1 (or whatever) repo that works with the same version of Vanilla. Don't know much about git, so that might not be a problem.

My first impression when you mentioned the size was "we do not live in the time of floppy discs any more!" but I had a quick look on the file sizes of some other forum software. The current Vanilla master branch was the biggest download I have found (although I only looked at 3 others). Adding the plugins will bloat that download even more, but I still think that there is not much difference between 4.something MB and 6 MB.   
But I guess this is some kind of a psychological question and you are right. I personally associate a bigger file size with inferior quality...    
   
But I guess you will stick to your politic of providing "the best" plugins with Vanilla ;)   
That's why I have done the following: I've searched google for "recent discussions" and from the 10 hits on the first page there were 8 Vanilla forums. 25% of them were using signatures, which is quite a big number ;) So even if you at Vanilla Inc don't like one or the other plugin, it might be popular "in the wild".   
You have a great resource that can help you in your decision finding process: you *know* which plugins are popular. How about bundling those with an installed base of >= 50%
If my lousy statistic is more or less correct, you also wouldn't have to pack Signatures to core ;)

**Comment by linc** [comment]
@R-J I think the sync issue is a function of letting the stable release lag too far behind, not the management of repos.

I'm hoping this plugin swap will be neutral in file size (Emotify is large, by plugin standards), but this does bring up a good point about our increasing weight, so I did this: https://github.com/vanilla/vanilla/pull/2432

In the end, we're curating plugins and recommending them by placing them in core. To put all or no addons in core is to forfeit that ability to recommend.

**Comment by linc** [comment]
Per conversation with @tburry, I've taken OpenID off the list to be removed.

I've also decided against cycling in Akismet, I think. It's track record with forum comments is spotty at best, and requires a paid subscription.

**Comment by linc** [comment]
For those interested, these (already) open source addons will be joining our public repository:

* Spoof
* PostCount
* Sitemaps
* SnowStorm
* StopAutoDraft

Why they've been stuck in our internal repo, I do not know.

**Comment by bleistivt** [comment]
I can't find vanillicon anywhere on github. Would be great to have in core, too.

**Comment by linc** [comment]
I didn't believe you until I went and found it.
