### ISSUE TITLE
Mentions Clearing after hitting return twice.

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#2478]
When mentioning someone via @mentions, hitting return twice completely clears the name.

**Comment by shooj** [comment]
Agreed that's the way it should work, but it's not working as it should.
What's happening is that hitting return once completely clears everything except the @ 
Hitting return again moves the cursor to the line below.
Hitting return a third time moves the cursor up to the right of  @ again
Repeat ad infinitum.

Using the tab key instead of the return key has the same effect.
Using Firefox instead of Chrome makes no difference.
Our forum is embedded inside an iframe, so I though it might work better if I used the non-embedded version directly at the vanillaforums.com URL. No difference.

Ideas?

**Comment by LauraMakesArt** [comment]
Shooj, I'm not sure if you misunderstood my original post, but the issue is now open for the devs to look at, and what you describe is precisely what I was reporting.

**Comment by shooj** [comment]
I did misunderstand. I thought you were addressing me instead of your devs. 

Fingers crossed.

**Comment by shooj** [comment]
Bumping. Any update?

**Comment by linc** [comment]
You can ask the community about recruiting assistance to fix this on the forum. http://vanillaforums.org/discussions

Please use comments here to contribute information or other assistance, not ping the dev team until your pet issue is fixed.

**Comment by bleistivt** [comment]
I'd suggest updating the library to the newest version:
https://github.com/ichord/At.js

It looks like the vanilla forums customizations mentioned here:
https://github.com/vanilla/vanilla/blob/master/js/library/jquery.atwho.js#L16-L28

...are now all possible through the plugin:
https://github.com/ichord/At.js/wiki/APIs#setiframe
https://github.com/ichord/At.js/wiki/Base-Document#custom-query-matcher
