### ISSUE TITLE
ArrayHasValue() returns false positive if array contains 0

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2527]
The following will result in a false positive because 0 == "string":
~~~
$Array = array(0, 'whatever', '...');
if (ArrayHasValue($Array, '_any_ string')) {
    echo 'False Positive!';
}
~~~

I think ArrayHasValue must use strict comparison for the in_array() function to avoid that error. But on the other hand using strict type comparison may break code that is working by now only because in_array("2", array(2,3,4)) is true.

If I thought it would be safe I would have made a PR for this...

**Comment by linc** [comment]
The idea of `ArrayHasValue` is that it's a recursive `in_array`. Since `in_array`'s default functionality is a non-strict comparison, and that's nearly the only way I ever see it used, I feel like this is just a typical PHP comparison problem to watch out for. If you stick the number zero into an array, woe unto thee.
