### ISSUE TITLE
BMPs result in "file failed to upload" error w/ Advanced Editor

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#2846]
Attempting to upload a BMP file with the Advanced Editor, even when it's specifically whitelisted, results in receiving a "file failed to upload" error.

**Expected result**: BMP is attached without issue.

**Comment by JulieVanilla** [comment]
Should have sprinted label.

**Comment by linc** [comment]
Did you try both the "select file" and drag & drop?

**Comment by JulieVanilla** [comment]
Confirmed that neither select file nor drag & drop works. Both throw the file failed to upload error.

**Comment by initvector** [comment]
There's nothing currently in Vanilla for handling bitmap uploads.  This is because PHP doesn't have the native ability to handle bitmap files.  It supports WBMP (wireless bitmaps), but not the BMP we all know and love.  I don't think there's any real way to make this happen without bringing in a third-party image library or investing significant time into making our own.

I vote we just leave BMPs in the past, where they belong.

**Comment by linc** [comment]
@initvector I don't think the goal here is to allow them as image uploads that embed or render, but rather to just make them an attachment, like a ZIP or PDF.

**Comment by JulieVanilla** [comment]
Confirming the desired action is to allow them to be attached, not necessarily rendered.

**Comment by initvector** [comment]
That makes perfect sense to me!  PR for that very thing is pending review.
