### ISSUE TITLE
Setup failing in 2.2

### ISSUE THREAD

**Issue by j-norwood-young** [vanilla/vanilla#2862]
Hi there

When I try run a setup on a clean database, it fails without a specific error. The red error bar shows up, but with content. 

I've isolated the problem to this command in `dashboard/models/class.permissionmodel.php`:

```
$this->SQL
->set($this->_Backtick($DefaultPermissions), '', false)
->replace('Permission', array(), array('RoleID' => 0, 'JunctionTable' => $JunctionTable, 'JunctionColumn' => $JunctionColumn), true);
```

This is called by `dashboard/settings/structure.php` at:

```
// Define the set of permissions that Garden uses.
$PermissionModel->define(array(
    'Garden.Email.View' => 'Garden.SignIn.Allow',
    'Garden.Settings.Manage',
    'Garden.Settings.View',
    'Garden.SignIn.Allow' => 1,
    'Garden.Users.Add',
    'Garden.Users.Edit',
    'Garden.Users.Delete',
    'Garden.Users.Approve',
    'Garden.Activity.Delete',
    'Garden.Activity.View' => 1,
    'Garden.Profiles.View' => 1,
    'Garden.Profiles.Edit' => 'Garden.SignIn.Allow',
    'Garden.Curation.Manage' => 'Garden.Moderation.Manage',
    'Garden.Moderation.Manage',
    'Garden.PersonalInfo.View' => 'Garden.Moderation.Manage',
    'Garden.AdvancedNotifications.Allow',
    'Garden.Community.Manage' => 'Garden.Settings.Manage'
));
```

Unfortunately I don't know enough about the app to know where to start fixing this.

I'm running on PHP 5.4.39 on OSX. Vanilla version 2.2.100.4.

**Comment by linc** [comment]
What is you MySQL version and do you have "strict mode" enabled?

**Comment by j-norwood-young** [comment]
```
mysql> SELECT @@GLOBAL.sql_mode;
+--------------------------------------------+
| @@GLOBAL.sql_mode                          |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
```

```
mysql> select @@VERSION;
+-----------+
| @@VERSION |
+-----------+
| 5.6.24    |
+-----------+
```

**Comment by linc** [comment]
Thanks!

**Comment by chanhong** [comment]
This sound like the same problem that I am having.  Thanks

**Comment by geoclicks** [comment]
@linc  same problem here with the latest master release as of a 6th Aug. Version 2.2.100.4 

SQL Mode -  STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |

and

SQL Version -  5.6.26-log

**Comment by geoclicks** [comment]
Was fixed by forcing MyISAM and disabling STRICT_TRANS_TABLES

Can the installer check before proceeding and advise the user? Was a bit of a pain to debug, for a brand new user. Thanks.

**Comment by linc** [comment]
I think I've tracked down this one. We're being a little too clever with our SQL in permissionmodel::define().

**Comment by linc** [comment]
In `permissionModel()->define()`, you send an array of permission names & default values which it sets up in the database. These come in 3 flavors:

    'Garden.Activity.Delete', // Varies by role, so no default is provided (value-only)
    'Garden.Activity.View' => 1, // All-role default, so we have a key-value pair.
    'Garden.Profiles.Edit' => 'Garden.SignIn.Allow', // Map this permission to an existing one, per-role.

In the `define()` method, it first deals with all the clearly-delineated defaults, then does:

    elseif (!$Structure->columnExists($Value) && array_key_exists($Value, $PermissionNames))
        $DefaultPermissions[$PermissionName] = $PermissionNames[$Value] ? 3 : 2;
    else {
        $DefaultPermissions[$PermissionName] = "`{$Value}`"; // default to another field
    }

This `$DefaultPermissions` collection MAY have either a `tinyint` OR a column name as its value for each permission at this point. Then we do:

    ->set($this->_Backtick($DefaultPermissions), '', false)
    ->replace('Permission', array(), array( 'RoleID' => 0, 'JunctionTable' => $JunctionTable, 'JunctionColumn' => $JunctionColumn ), true);

This call to `replace()` is what's tripping up MySQL's `STRICT_TRANS_TABLES` mode, because it's pre-checking for `tinyint` values that it does not have yet.

It seems like the solution here is to do 2 passes: one of our non-mapped permissions, then a second one after we've already queried & mapped those values in code. Alternatively, we could do the super dirty thing and turn off `STRICT_TRANS_TABLES` while it runs, which seems like a bad idea. However, the 2-pass method involves rewriting a lot of the `define()` method and making it less neat. I've already dead-ended twice trying to do this properly.

**Comment by chanhong** [comment]
If this only happen in setup which only one time then it seems disable STRICT_TRANS_TABLES for the setup duration would be the least amount of work to get around this issue, I think.
