### ISSUE TITLE
Remove deprecated jQuery.selector in jquery.popup.js

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3053]
jquery.popup.js makes use of jQuery's .selector property which is deprecated and may be removed in the future: "The .selector property was deprecated in jQuery 1.7 and is only maintained to the extent needed for supporting .live() in the jQuery Migrate plugin."

Solution:
replace 

```
var delegateToSelector = this.selector;
$(document).on('click', delegateToSelector, function() {
```

with 

```
this.click(function() {
```

Problem: Some themes are incompatible with this change, e.g. Vanilla bootstrap theme which does

```
$(document)
      .on('popupLoading', function () {
        $(overlay).each(preparePopup);
      })
      .on('popupReveal', function () {
        $(overlay).each(revealPopup);
      })
      .on('popupClose', function (e) {
        $(overlay).each(closePopup);
      });

    var confirmPopupEls = [
      'a.Delete'
    , 'a.DeleteComment'
    , 'a.DeleteFile'
    , 'a.PopConfirm'
    , 'a.ClearConversation'
    , 'ul#DP_Remove a'
    ];

    // When only a confirmation modal is shown, the "popupLoading" and
    // "popupReveal" events are never triggered. Manually trigger them to make
    // sure that the modal is actually shown.
    $(document).on('click', confirmPopupEls.join(), function (e) {
      $(document).trigger('popupLoading');

      setTimeout(function () {
        $(document).trigger('popupReveal');
      }, 150);
    });
```

in its main.js.

This won't work any more after applying the suggested change since the event is no longer delegated from document but directly captured at the popup opening element (e.g. a link) and doesn't bubble up to the event handlers defined by the theme above.

Still, the change is necessary to make Vanilla future proof and the js code / event handling cleaner.

**Comment by bleistivt** [comment]
Those are not equivalent. 
    $(document).on('click', selector, function () ...
will work for dynamically added element, directly adding to the elements does not.  
Attaching everything to `document` is essentially what `live()` does.

This can be done without breaking backwards compatibility.
e.g. you could also just pass in a selector like I did here https://github.com/vanilla/vanilla/commit/d3abda8264399e62c30d338d4c78356afabbf7e7

Events called with jQuerys `.trigger()` bubble up the DOM tree by default (as do most javascript events). This is not caused by the delegation mechanism.

**Comment by mtschirs** [comment]
@bleistivt Correct, they are not equivalent. However, this is why I think this.on('click', handler) is better than $(document).on('click', selector, handler):

* $(document).on('click', selector, handler) requires passing the selector via argument in $.fn.popup(). All 100+ calls to $(...).popup() would need to be considered for replacement by $(...).popup(selector, ...) whereas this.on('click', handler) would just require few themes to be tested for compatibility.

* Delegating the click event via $(document).on() but directly capturing the mouseover and mouseout event via this.mouseover() and this.mouseout() is inconsistent.

* Capturing events close to their source is a more local and therefore cleaner approach IMHO (correct me if I am wrong). It allows for a fully working popups with event handling outside of the DOM e.g. by `a = document.createElement("a"); a.href = "/discussions"; a.className = "Popup"; a.click()` without need for `document.body.appendChild(a);`

**Comment by bleistivt** [comment]
Making a compatibility-breaking change to the popup library is the wrong apporach imo.

> All 100+ calls to $(...).popup() would need to be considered for replacement by $(...).popup(selector, ...) whereas this.on('click', handler) would just require all themes to be tested for compatibility.

Even if it is a 100 calls, you can theoretically do it in one pull request here. But you cannot control themes and plugins.

Just did a test. Looks like they are going to remove it as of jQuery 3.0: http://jsfiddle.net/Lff9ryud/

> Delegating the click event via $(document).on() but directly capturing the mouseover and mouseout event via this.mouseover() and this.mouseout() is inconsistent.

Yes, it is inconsistent, but the "mouseOverClass" argument and the standard class `.Popable` is not used anywhere so it probably wasn't noticed.

> Capturing events close to their source is a more local and therefore cleaner approach IMHO. It allows for fully working popups with event handling outside of the DOM

I don't think this is useful. What are you going to do with a popup you can't see or open?

You should always be able to do something like this:

    $(document).on('popupLoading', function () {
        //...
    })

If the popup events don't bubble up the DOM tree when you bind them directly to `this`, **something else is broken.** This is the standard behaviour for events in javascript. Themes and plugins should be able to rely on this.

I think there are 2 problems in Vanillas js libraries:

 * Things get added to the DOM dynamically in some places (e.g. after "JSONtarget" processing) without a proper event to subscribe to. This is because `.live()` and `.livequery()` has been used for subscribing to events at document level and to DOM mutations.

 * Most of the libraries can't be easily updated to a newer version because they have been modified. jquery.popup.js and jquery.atwho.js are perfect examples for this.

You can see that jquery.popup.js is part of both those problems.

I would rather research if the handlers can be reattached by handling the proper events when dynamic content is added and adding those events when they are missing.

**Comment by mtschirs** [comment]
I don't get this argument:
> Making a compatibility-breaking change to the popup library is the wrong apporach imo.
> Even if it is a 100 calls, you can theoretically do it in one pull request here. But you cannot control themes and plugins.

Isn't adding the selector arg to $.fn.popup() also a compatibility-breaking change that requires themes and plugins to be updated?

The out-of-DOM technic is useful for programatically creating popups as detailed here: http://vanillaforums.org/discussion/25089/opening-popup-programatically
This might be fixed though if my current PR will be accepted.

> If the popup events don't bubble up the DOM tree when you bind them directly to this, something else is broken. This is the standard behaviour for events in javascript. Themes and plugins should be able to rely on this.

The thing that is broken here is: popup.jquery.js doesn't create these events in the first place if the settings contain `confirm: true`. Thus, themes such as bootstrap try to work around this by listening for the 'click' event and then manually creating the 'popupLoading' & co. events. This won't work any more if the 'click' event is captured at the source already instead of further up in the document. The solution here would be to get rid of the need for these workarounds. Additionally, one could remove the current implicit `event.stopPropagation()` from the click handler (caused by `return false`);

**Comment by mtschirs** [comment]
I just tested it; replacing
```
var delegateToSelector = this.selector;
$(document).on('click', delegateToSelector, function() {
    ...
    return false;
}
```
with
```
this.click(function(e) {
    ...
    e.preventDefault();
}
```
preserves compatibility with the current jquery.popup.js.

**Comment by linc** [comment]
Did #3052 resolve this?

**Comment by mtschirs** [comment]
@Linc No, that was an independent change.

**Comment by charrondev** [comment]
Vanilla's frontend is rapidly moving away from jQuery and towards React & Vanilla javascript. There is no intent to ever upgrade the jQuery version in Vanilla. Only to remove it from futures pages.
