### ISSUE TITLE
Remove UpdateModel and core functions proxyRequest() + proxyHead()

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3055]
UpdateModel contains all kinds of old legacy code. Move UpdateModel->runStructure() into the core (and fix https://github.com/vanilla/vanilla/issues/2931) and remove the rest.

proxyRequest() and proxyHead() from "library/core/functions.general.php" are dangerous and should never be used; its only legitimate use-case might have been the proxyConnect plugin which is since long deprecated.

**Comment by linc** [comment]
I think I'd like to clean out the unused parts of it rather than remove it entirely. The bad code in there is an aborted attempt to provide self-updating functionality to Vanilla, which seems like a still-valid long term goal. So I think removing the entire model would be a step in the wrong direction.

**Comment by linc** [comment]
I'm pretty sure `proxyRequest()` and `proxyHead()` are fine to work out of core.

**Comment by linc** [comment]
The updatemodel should mostly be moved to the addons directory app in the `community` repo.
