### ISSUE TITLE
Garden.Analytics.Enabled=false disables view counting for discussions

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3071]
The vanilla application sets up a gdn_Statistics_Tick_Handler() in its class.hooks.php. This handler increases the current discussion's view counter when a discussion or discussion comment has been requested.

Setting Garden.Analytics.Enabled to false causes Gdn_Statistics::check() not to call Gdn::controller()->addDefinition('AnalyticsTask', 'tick') which in turn disables the ajax request to /settings/analyticsTick and thus the creation of the 'Tick' event. As a result, Vanilla's gdn_Statistics_Tick_Handler() is never called.

**Comment by JasonBarnabe** [comment]
I can confirm this is an issue in 2.2.

**Comment by charrondev** [comment]
I'm failing to see how this is a bug. Disabling Analytics _will_ disable the analytics tick..

If I'm missing something here, feel free to open a new issue with more detail of the use cases that are failing here.

**Comment by JasonBarnabe** [comment]
I don't really remember this, but I believe the intention is to not report anything to the external server while continuing to have view counts available locally.

**Comment by charrondev** [comment]
From what I can see that check is the only place I can even see that configuration flag used has been untouched since the original version of Vanilla that we have history for.

In order to proceed on this issue it would need to be more clearly outlined in any case, because it is not obvious what the behaviour should be. It needs to start with a list of expected things that should happen  on an analytics tick with/without the configuration flag set, and what is actually happening then we can decide on what the desired behaviour of the configuration flag should be.
