### ISSUE TITLE
IPv6 IPs returning as 0.0.0.2

### ISSUE THREAD

**Issue by FerusGrim** [vanilla/vanilla#3132]
I've searched this issue pretty extensively and found a number of tickets which seemed to have resolved this issue. I believe something about the length of the protocol wasn't supported in the database. It seems as though a push for this has been made, however through design or some bug, people who access our site through IPv6 (myself included) are having their IPs shown as 0.0.0.2.

This poses a number of problems, most of all security when trying to permanently ban nuisance users.

![ss 2015-09-24 at 08 21 04](https://cloud.githubusercontent.com/assets/5481250/10090154/e26264fe-62f9-11e5-88d7-22d1c2c0966a.png)

![ss 2015-09-24 at 08 24 21](https://cloud.githubusercontent.com/assets/5481250/10090181/49bd8296-62fa-11e5-9c6d-6b977f2b1edc.png)

If there's some kind of fix or update for this, or it's simply a bug that we've created somehow, any idea on where I can locate and solve this issue would be extremely appreciated.

**Comment by FerusGrim** [comment]
After going through the comments in some of the previous issues/PRs regarding this, it seems as though the consensus is that support just... won't be added?

The majority of ISPs give out IPv6 addresses to users, nowadays. Sure, they're huge and a bit ugly, but dropping support because of that isn't a very good solution. They're widely in use, and I'd be forced to ostracize any kind of IP-based research/moderation on users when they could just force an IPv6 connection and have that data be lost to my team.

Are we sure this isn't an issue we can revisit? Or is my information outdated?

**Comment by FerusGrim** [comment]
The main people arguing for/against this addition, respectively, seemed to have been @linc and @tburry. If it would be possible to get their input on this matter, that would be great.

**Comment by kaecyra** [comment]
IPv6 support will be added. IPv4 is essentially deprecated and will be superseded by v6 in the terrifyingly near future, so we cannot avoid it. That said, there is currently no timeline for when v6 will be supported in the product.

**Comment by linc** [comment]
https://www.arin.net/announcements/2015/20150924.html

**Comment by linc** [comment]
There's a few issues with IPv6 support:

* Making changes to these tables is going to be horrific for some databases. There's this and [other technical considerations](https://github.com/vanilla/vanilla/pull/2110#issuecomment-56859862) @tburry raised, including: If we're gonna initiate a downtime-causing database update, what else should we use that window to accomplish?
* Displaying IPv6 addresses to moderators is probably silly. They're not really human-consumable the way IPv4 was, so it because superfluous meta data that junks up the view. What do we replace it with that provides value? (We have ideas, but it's a bit of a tangent for this issue).
* IP banning is pretty archaic kludge move and we're not fans of it. This seems like the point at which we need a better moderation workflow to obsolete it, and that's on our 2016 roadmap.

So this is actually a really big feature for us, not something we can hotfix real quick. It seems like, strategically, the best course of action is to wait for more pieces to be in place.

**Comment by FerusGrim** [comment]
While writing up my PR, I ran into a few of the issues that you suggest. It's annoying, for sure, but adding real support is more difficult than I had originally thought it would be.

**Comment by linc** [comment]
We definitely appreciate you taking the time to consider it and propose solutions!

**Comment by linc** [comment]
We've refactored our IP handling for 2.4 so I am closing this.
