### ISSUE TITLE
Emoji suggestions don't include the alternate emoji code for autocomplete

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3360]
When typing an emoticon like `:D`, the dropdown of suggested emojis (using EmojiSet) will suggest items like `:dizzy:` and `:disappointed:` instead of the completed `:D`, even though that emoji exists through the set. (Tested with Yahoo and Twitter and Apple)

This can cause issues if users don't realize they can just hit spacebar to go ahead and type `:D` anyhow.

**Expected behaviour**

The alternate emoji codes should show up in the autocomplete list.

**Comment by initvector** [comment]
### Overview of emoji autocomplete workflow
Emoji data for autocompletion resides in `gdn.meta.emoji`.  That JavaScript variable is populated around [emoji.php:274](https://github.com/vanilla/vanilla/blob/722076877ade6bd5a243f2bc6bfa4ecc65125842/library/core/class.emoji.php#L274).

The autocomplete for emoji is handled by [gdn.atCompleteInit](https://github.com/vanilla/vanilla/blob/722076877ade6bd5a243f2bc6bfa4ecc65125842/js/global.js#L1454) in [global.js](https://github.com/vanilla/vanilla/blob/722076877ade6bd5a243f2bc6bfa4ecc65125842/js/global.js).  The basic setup for autocompletion of emojis is as follows:

1. Grab the list of emoji from `gdn.meta.emoji.emoji`.
2. Iterate through the list and build `emojiList`, an array of objects, based on the key/value pairs in `gdn.meta.emoji.emoji`.  For example, one of the key/value pairs is `smiley: "smiley.png"`.  This would become `{'name': "smiley", 'filename': "smiley.png", 'basename': "smiley", ".png"}`.  Each emoji object becomes a member of the `emojiList` array.
3. The emoji autocomplete routine is [triggered by a colon](https://github.com/vanilla/vanilla/blob/722076877ade6bd5a243f2bc6bfa4ecc65125842/js/global.js#L1725).
4. The autocomplete functionality is powered by our customized version of [At.js](https://github.com/vanilla/vanilla/blob/722076877ade6bd5a243f2bc6bfa4ecc65125842/js/library/jquery.atwho.js)

### Issues needing to be addressed before implementation
* Aliases aren't included in the list of suggestions, because they aren't saved in `gdn.meta.emoji.emoji` to begin with.  We can add them as separate members of the `gdn.meta.emoji` collection or we can revise the way `gdn.meta.emoji` is built to include aliases.  The latter would require also changing the way `emojiList` is built in the page.
* Since emoji autocomplete only happens on inputting a colon, it's going to be a little more involved to make emoji work that don't begin with a colon (e.g. `=)`, `;)`, `D:` and `B)`).  I can't say for sure it's even possible with the current autocompletion library.
* Every emoji that is completed with autocomplete gets wrapped in colons.  This means that `:D` would become `::D:`.  We'll have to avoid wrapping emoji aliases in colons, while still maintaining that wrap for the standard emoji codes.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
