### ISSUE TITLE
Show Editor's options on mobile

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#3433]
Mobile advanced editor seems to be missing strikeout, list, link, and alignment tools regardless of if its in html, bbc, or wysiwyg mode. I assume this is due to spacing, but the link functionality should be reconsidered, since its important for standard posts, and being absent from wysiwyg mode is a bit cumbersome.

**Comment by BallOfSpray** [comment]
Looks like this thread hasn't gotten any attention. Laura submitted it for me based on issues in my forum. My vanillaforum is embedded inside of my Joomla site. 

The problem is when a user pastes a long link the horizontal frame is stretched and the page looks very bad from an iPhone.  The lack of the link tool has turned out to be a source of significant heartburn in my community. I have to look at every thread daily to find long link and correct them back to a shorts.

I would be very happy to lose the emoji or formatting buttons but really need the link button. 

See http://www.ballofspray.com/forum

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
