### ISSUE TITLE
Avatar change should use protocol-agnostic image link in activity

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3485]
Changing your avatar creates an activity record with a `Story` of an image tag. This breaks when switching to SSL from non-SSL.

**Comment by charrondev** [comment]
I'm removing the "Good first contribution" label hear because I feel there is an inherit limitation in the structure of the activity feed here.

There is no proper way to implement this without first changing the structure of an activity story to be structured data like JSON.

Parsing HTML in this way poses other issues like serving to non-HTML clients, being stuck with old HTML structures as themes evolve, and handling i18n properly.

**Comment by linc** [comment]
I don't understand. The fix doesn't need to be retroactive. It just needs to change what it's jamming into the HTML field to remove the `http[s]:`.

**Comment by charrondev** [comment]
I misunderstood here I guess, although this seems like it has much less utility. Who has SSL setup, but would like to be able to serve their activity items without SSL? What's the use case?

I see a lot more utility in being able to update older records to now use `https://`.
