### ISSUE TITLE
Click on image attachment thumbnail should show modal instead of download prompt

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3517]
We have a conundrum about the behavior when click an image _thumbnail_. We added the `download` tag here: https://github.com/vanilla/vanilla/commit/475d0ad33827170a45246667d173954c68acfcef which is great because it preserves the original name. But it also creates non-sequitur behavior for images because folks expect a zoom, not a download prompt (which I agree is better). Removing that tag also means *every* attachment loses its nice save name, so that's no good either. My compromise solution: intercept it with Javascript if it's an image and show a modal / shadowbox of the enlarged image.

**Comment by sonicmouse** [comment]
I'm use the WYSIWYG feature in vanilla. It's great, but, in chrome thumbnails download instead of opening in a new tab or window. This is really ugly for users. I know this has something to do with what you are talking about.

Can't you simply add `Content-Disposition` to the header of the image? Like:

`Content-Disposition: inline;filename="the_filename.png"`

This makes it so Chrome opens it in the current window instead of downloading it to file.

**Comment by linc** [comment]
Closed by https://github.com/vanilla/vanilla/pull/3587
