### ISSUE TITLE
jquery.gardenhandleajaxform.js says $frm.parents is not a function when using class AjaxForm

### ISSUE THREAD

**Issue by Csabbencs** [vanilla/vanilla#3538]
When using class 'AjaxForm' together with jquery.gardenhandleajaxform.js for 

> "  // This turns any form into a "post-in-place" form so it is ajaxed to save
>    // without a refresh. The form must be within an element with the "AjaxForm"
>    // class."

javascript error occurs: $frm.parents

It's been there from the start (vanilla 2.0), but the core doesn't use it (and I guess nobody else), so this must be the reason that the issue hasn't popped up yet.

I recommend the following 4 pieces of code change:
Line 27 and line 40:
-`$frm.parents($(handle).selector).html(json.Data);`
+`$(handle).html(json.Data);`
Line 38:
-`$frm.find('span.Progress').remove();`
+`$(handle).find('span.Progress').remove();`
Line 56:
-`$($(handle).selector).handleAjaxForm(options);`
+`$(handle).handleAjaxForm(options);`

**Comment by charrondev** [comment]
I'm closing this because `gardenhandleajaxform` has no place in the future of Vanilla's frontend. We have been building up a library of new frontend components in `library/src/scripts` and we don't use jquery or auto-binding forms anywhere. The only implementation I could find anywhere was in the `/entry` pages which will eventually be replaced with API driven authenticate pages (available behind the `Feature.AuthenticationAPI.Enable` config flag at `/authenticate/signin`) on the latest master branches.
