### ISSUE TITLE
Performance issue with announcements - needs index

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3566]
The Announce column is not indexed (in the Discussion table) and the resulting query created by calling `$discussionModel->getAnnounements()` is pretty slow when you have a good amount of discussions.

**Comment by DaazKu** [comment]
That should do the trick:
```CREATE INDEX IX_Discussion_AnnounceCategory ON GDN_Discussion (‘Announce’, ‘CategoryID’)```

**Comment by charrondev** [comment]
@DaazKu @initvector Do you have any idea if this is still an issue?

**Comment by initvector** [comment]
I am assuming this is still technically an issue in so far as there isn't a specific index for these columns. This probably isn't a commonly-reported issue (and hence hasn't seen much traction in almost three years), because Vanilla should be able to [cache announcements](https://github.com/vanilla/vanilla/blob/927939b4a1fe582c71ca3947d75c7e5439848a56/applications/vanilla/models/class.discussionmodel.php#L1131) when using the `getAnnouncements` method in `DiscussionModel`.
