### ISSUE TITLE
Serialization Present in Non-database Areas

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3749]
Update to `dbencode`/`dbdecode`

- [x] applications/dashboard/controllers/class.entrycontroller.php: Cookie contents stashed with serialize
- [x] applications/dashboard/controllers/class.settingscontroller.php: addUpdateCheck uses Gdn_Format::serialize for value of UpdateChecks JavaScript definition
- [x] applications/dashboard/models/class.updatemodel.php: serialize used on addon requirements
- [x] library/core/class.format.php: image uses serialize

Leave As-Is

- [x] library/core/class.cache.php: serialize used on values for caching
- [x] library/core/class.memcached.php: serialize used on values for caching
- [x] library/core/class.passwordhash.php: unserialize used in checkPassword's xenforo routine
- [x] library/core/class.pluginmanager.php: availablePlugins, indexSearchPath serialize used in hashing dir contents
- [x] library/core/class.thememanager.php: availableThemes serialize used in hashing dir contents

**Comment by tburry** [comment]
I checked off ones that should stay as is. I'm not sure about _parseRoute. Can you add that as another task and put it on hold?

**Comment by initvector** [comment]
I've created a [dedicated task for `Gdn_Router::_parseRoute`](https://github.com/vanilla/vanilla/issues/4767) and removed it from the current task's checklist.

**Comment by initvector** [comment]
> applications/dashboard/controllers/class.settingscontroller.php: addUpdateCheck uses Gdn_Format::serialize for value of UpdateChecks JavaScript definition

Looks like this was addressed with [`65d4035`](https://github.com/vanilla/vanilla/commit/65d4035836ad584c6473676a8c577ea1eb169bfb#diff-37d8298602c7bcd350252f9bdca900fcR988)

**Comment by initvector** [comment]
> library/core/class.configuration.php: unserialize used on some config values

[`Gdn_Configuration::get`](https://github.com/vanilla/vanilla/blob/f4fddfa1d11a59e18a1187139428d3f529c4a6fd/library/core/class.configuration.php#L278) and [`Gdn_ConfigurationSource::get`](https://github.com/vanilla/vanilla/blob/f4fddfa1d11a59e18a1187139428d3f529c4a6fd/library/core/class.configuration.php#L1275) both run their values through [`Gdn_Format::unserialize`](https://github.com/vanilla/vanilla/blob/f4fddfa1d11a59e18a1187139428d3f529c4a6fd/library/core/class.format.php#L2073) if they're a string.  The problem is this function checks the format of these strings before determining if they should be run through `unserialize`, `json_decode` *or* returning the original value, unmodified.  Currently `dbdecode` only supports `unserialize` and is built to fail if an invalid serialized value is passed to it.  This means if we just swap out both instance with `dbdecode`, they'll often return `false` and fundamentally break Vanilla.

1. Leave `Gdn_Format::unserialize` where it is in `Gdn_Configuration` and `Gdn_ConfigurationSource`.
2. Apply some of the format detection logic from `Gdn_Format::unserialize` to these two classes, before attempting to run them through `dbdecode` or `json_decode`, although we'll likely to revisit this if we move to switch up `dbdecode` to use JSON, instead of PHP serialization.
3. Move the format detection from `Gdn_Format::unserialize` to `dbdecode`.  This will mean we are fundamentally changing the way `dbdecode` works, because it will no longer return `false` on invalid values.

**Comment by initvector** [comment]
Per @linc I'm going to proceed with the first option: leaving `Gdn_Format::unserialize` in `Gdn_Configuration` for now.

I've opened an issue to address this area, specifically: https://github.com/vanilla/vanilla/issues/4770
