### ISSUE TITLE
How to make this ?

### ISSUE THREAD

**Issue by GabrielEnraged** [vanilla/vanilla#3778]
Hello Vanilla forums community, i just want to know how to make display of categories like that : 
http://bestoffernet.com/vb/

Screenshots : 

![capture](https://cloud.githubusercontent.com/assets/18049206/14763205/e08ed70c-098e-11e6-8270-6a3106332f55.JPG)

**Comment by R-J** [comment]
Questions like that should better be asked (and have been asked before) in the [support forum](vanillaforums.org) 

Go to yourforum.com/dashboard/settings/homepage and choose "Categories" as home page and "Table Layout" for Discussions Layout and Category Layout.

In the categories settings, "Display root categories as headings." has to be checked so that you can have "named groups" for your categories.

The theme used is Bootstrap.

If any questions concerning how to use Vanilla are left, join the the [support forum](vanillaforums.org) :-)

**Comment by GabrielEnraged** [comment]
Thanks men, it's work fine, but, after this work fine, there is a bug : 

I can't save the settings, i explain : 
After clicking on save, and go to my forum, the settings as not being saved....
To correct this, i have backup the database and delete him.

After, it work fine so, thanks you :) !!

**Comment by linc** [comment]
For help using your Vanilla Forum, please visit the community site at https://vanillaforums.org/discussions. This area is for technical issues.
