### ISSUE TITLE
Dashboard v3 homepage styling

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3855]
Requires #3854.

The functionality of the dashboard should be complete, not the styling is left.

**Comment by R-J** [comment]
I was interested in he new design and just tried it. I'm not sure if you are already in a state where "user" feedback is useful, but here are my findings & thoughts:

Thoughts on div#Head:
1. Why not make it a header html element?
2. div.head-link has round borders while div.head-user has not. They are simple links, so why are they visually different? Different styling signals different functionality or behaviour to me.
3. Why are they upper cased? The rectangular links look exactly as buttons, only that they are upper cased. Even those "buttons" that are only links (Add Category) are not upper cased so this is not to distinguish between action & link but seems to be only a matter of taste. I personally would prefer a uniform look for uniform functionality.

nav#Panel (great that it's a nav element!)
1. While the links in the top nav are upper cased, in the panel the non-links are upper cased. This is a contradiction that shouldn't be made.
2. div.Box h4 and the links in the li elements look too similar! They are separated by an indention, a (maybe a little bit too) decent  line and the casening, but the caseining is meaningless by now (see 1.). In fact I tried to click on the headings. Maybe making them accordeons would help: this way they would offer a functionality. Since the Panel is way too long to fit on a normal monitor, this might be a good idea anyway. I guess I would prefer if they have a different background in order to clearly separate them from their links.

Otherwise I like the look and the color composition very much!

Here are some small glitches and my personal opinion on several other points
1. div.Help.Aside is unstyled
2. I don't like "transparent" buttons, but if you keep them, you might think of styling border and color different. I think the bright blue color has not enough contrast.
3. The dark blue of div.PageInfo could be a little brighter though and the font should be the same
4. Unfocused InbutBox are very hard to be identified as input elements. The first look at the Homepage Title on /dashboard/settings/banner made me think I was seeing a label and not an input element.
5. The green check mark in /dashboard/settings/homepage (a.Choice) doesn't really fit to the new design.
6. Buttons often (always?) have no padding and are directly "attached" to the Panel visually (e.g. /dashboard/settings/avatars)
7. I think it is span.ActivateSlider which needs styling: /dashboard/settings/emailstyles
The Edit/Delete buttons on /dashboard/user look too narrow. Maybe they can be replaced with icons?
8. The yellow background for "Embedding is currently DISABLED." looks retro: /dashboard/embed/comments. 
9. The tabs in /settings/plugins have the old styling
10. Links in plugin/addon descriptions are not recognizable as links.
11. There should be some whitespace between the dropdown and the button in /dashboard/settings/locales
12. Popups (e.g. if you add a route) have mixture of old style and new
13. If you already started using semantic html for the panel, why not use header, main and footer? And certainly aside for div.Help.Aside

But don't let me be misunderstood because I wrote that much: I **really** like the design!

**Comment by tburry** [comment]
Hey thanks for your enthusiasm @R-J. I know you understand that this is very much a WIP right now. We have a long way to go including some iterations after we launch the new design. I'm not sure how many issues here will be relevant as we continue to pick away at stuff.

If you can keep your feedback to general stuff that would be in the master view for now that would be great. Individual pages will haven't been fully looked at or even design.

In terms of where to post comments, I'm guessing this issue is not the place. Maybe PR #3909 would be better, but I really want to make sure we don't get a stampede of feedback before we've completed an alpha version.

We're very excited about the new design too. We hired our first designer a couple of months ago so expect more attention being paid to how stuff looks in the future.
