### ISSUE TITLE
Research helper methods the TagModel should have

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3969]
I want the tags to be a central part of the core API. A lot of plugins already use them. Let's look at what stuff we can add to make it easier for plugins to work with tags.

- Can I convert tag slugs to tag IDs easily?
- Can I add new tags easily?
- Can I filter tag arrays returned from other methods easily?
- etc.

**Comment by DaazKu** [comment]
[As per that comment](https://github.com/vanilla/vanilla/issues/3972#issuecomment-222517561):
> There are currently issues with tag Name/Type.
For example if a tag X of type Y is defined and a user would be to define a tag X of no type (since it is used defined it doesn't have a type) the tagging plugin would treat tag X-notype as tag X-Y [because it search only by name](https://github.com/vanilla/vanilla/blob/473112523e207c3b2c913b9a86f4bdcd93503368/plugins/Tagging/class.tagmodel.php#L410).
We should either drop the Name-Type combination of make it so that you HAVE to use Name-Type everywhere.

We currently have a big problem converting slugs to ID since the `Type` field is lost in the wild.
Once that problem is fixed, one way or another, some useful methods would be:

- a `joinTags` function that works on any data set. Not just discussions 
- `getTagsOfType(mixed)` which could get a type or an array of types and return all tags of these types.

If we end up keeping the Type field *Filtering tags by type* is an obvious helper function we want.

**Comment by DaazKu** [comment]
Where do we go from here?

**Comment by tburry** [comment]
I think that particular piece of code could be a bug since the types are passed as a parameter to the method.

**Comment by DaazKu** [comment]
Closing this since the main question as been answered here: https://github.com/vanilla/vanilla/issues/3969#issuecomment-222799565
