### ISSUE TITLE
Brainstorm tag API changes/enhancements

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3972]

**Comment by DaazKu** [comment]
There are currently issues with tag Name/Type.
For example if a tag X of type Y was defined and a user would be to define a tag X of (no type since it is used defined) the tagging plugin would threat tag X-notype as tag X-Y because it search by name only.
We should either drop the Name-Type combination of make it so that you HAVE to use Name-Type everywhere.

**Comment by DaazKu** [comment]
We should also add an endpoint to see every tagged elements of a certain type. This is something that will be useful for the RoleTracker plugin. See every tracked discussions in one place.

**Comment by DaazKu** [comment]
Brainstorming alone is not cool :P

So:
https://github.com/vanilla/vanilla/issues/3972#issuecomment-222517561 may potentially cause problems so I'm not sure if we want to do that now.
https://github.com/vanilla/vanilla/issues/3972#issuecomment-232449587 I think that could be a nice addition!

@tburry ?

**Comment by linc** [comment]
Talk to him in person and summarize here afterward.

**Comment by DaazKu** [comment]
Recap:

- Find out is the categoryID for tags is still used and why.
- We should put a unique constraint on Name/Type.
- Create a new model in library/Vanilla which will be our baseline to improve tagging.
- Update the tags to integrate Types better.
   - The type should appear in the URL when the tag is not the "default/(empty)" type
- Check the advanced search and the other plugins to make sure that the changes work well.
   - In advanced search tags will be searched by names only (for now). This means that the search could return result for multiple tag type.
