### ISSUE TITLE
Vanilla should not override php logging

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4019]
Currently, Vanilla has a `Garden.Errors.LogEnabled` setting which defaults to FALSE in config-defaults.php

This setting, for whatever reason in the past, interferes with PHP's error logging mechanisms and makes life difficult on the server admin side. It should be removed in favour of allowing PHP itself to log errors to file if it wants to. 

There is also a `Garden.Errors.LogFile` setting which seems to somehow allow modifying the target of PHP logs. This should be totally removed, again in favour of allowing PHP to decide where logs are sent.

**Comment by tburry** [comment]
## First PR

The point of this PR is to pass Vanilla's errors through to the error log using a more native PHP methodology.

- Look at log_errors instead of Garden.Errors.LogEnabled (remove the config setting altogether).
- Make an error_log wrapper that looks at log_errors and will use the Garden.Errors.LogFile if set.
- Call the error_log wrapper wherever possible in functions.error
- Should we write a format message function that takes a message, optional filename and line number and formats it in the way PHP formats an error message?

## Second PR

The point of this PR is to respect the error_reporting INI setting unless we are debugging.

- Don't set the error_reporting level in the index.php.
- The default set_error_handler should not handle low level errors (E_NOTICE, E_USER_NOTICE, E_DEPRECATED, E_USER_DEPRECATED, E_STRICT, etc.)
- The call to debug() should elevate error_reporting to E_ALL & ~E_STRICT and call set_error_handler again with E_ALL & ~E_STRICT.

**Comment by kaecyra** [comment]
Errors should DEFINITELY be logged in PHP error format, since this directly impacts the ability for us to aggregate errors.
