### ISSUE TITLE
Cannot save array into config

### ISSUE THREAD

**Issue by rbrahmson** [vanilla/vanilla#4043]
I have a plugin (DiscussionAlert) that has a configuration screen that displays the defined categories and let the admin select categories via checkboxes.  The selection is saved as an array in config.php.  

_Works fine in 2.2, breaks in 2.3 - the values are not saved in the config.php file._

This is not an access issue - other variables are saved just fine.

**To reproduce:** look at the source of the plugin:
https://github.com/rbrahmson/VanillaPlugins/blob/master/DiscussionAlert/class.DiscussionAlert.plugin.php#L179-L223

The unsaved setting in question is 'Plugins.DiscussionAlert.CategoryNums'.

**Comment by linc** [comment]
We did change this; we no longer allow arrays to be saved to the config. We should add proper documentation / error messages and let folks know their plugins need to be updated. It will still *read* an existing array afaik, just not write new ones. This allows plugin authors to seamlessly update their plugins.

**Comment by rbrahmson** [comment]
Why would you make a change that breaks compatibility? 

Is there another way to save a list of elements into config?

**Comment by linc** [comment]
* Performance.
* Moving to a JSON-formatted config in the future.
* Code maintenance (volume of code > value).
* Redundancy / Better ways to do the same thing (Our dot syntax allows using multiple sub-keys as an array when you pull it out).
* A rarely-used feature - I think all of Vanilla's code used it once or twice, ever.

Yes, save it as a comma-separated list, or use multiple keys.

**Comment by rbrahmson** [comment]
The issue is not how I save is in config but _how Vanilla saves it_.  I am using "$configurationModule->initialize(" with a " 'Control' => 'CheckBoxList',".

I feel that if you want to change how it is saved in config then you need to do it so that the Checkboxlist is saving and reading it differently (however you like - I didn't care much that it was an array), transparent to the caller (so as to not break plugins/apps).

**Comment by R-J** [comment]
I'm used to create simple setting screens like that:

~~~
$categories = CategoryModel::categories();
unset($categories[-1]);

$configurationModule = new ConfigurationModule($sender);

$configurationModule->initialize(
    [
        'Plugin.CategoryIDs' => [
            'Control' => 'CheckBoxList',
            'LabelCode' => 'Categories',
            'Items' => $categories,
            'Options' => ['ValueField' => 'CategoryID', 'TextField' => 'Name']
        ]
    ]
);

$configurationModule->renderAll();
~~~

Since the result of a CheckBoxList is an array, the control CheckBoxList is not usable like that any more in the configurationModule. In the configurationModule there is this code:
~~~
                $Value = $Form->getFormValue($Name);

                // Trim all incoming values by default.
                if (val('Trim', $Row, true)) {
                    $Value = trim($Value);
                }
~~~
That is the part which makes checkboxlists array value to an empty string and this is the code which makes the current behavior a **bug in the configurationModule**. A totally valid construct leads to data loss.

Either the checkboxlist mustn't be supported any more by the configurationModule (which would be a shame) or there must be some workaround found. The only halfways "elegant" way I can think of would be to convert the example above for CategoryIDs [1,2,3,4] where e.g. category 2 and 4 where checked would result to the following:
~~~
removeFromConfig('Plugin.CategoryIDs.1');
saveToConfig('Plugin.CategoryIDs.2', true);
removeFromConfig('Plugin.CategoryIDs.3');
saveToConfig('Plugin.CategoryIDs.4', true);
~~~

That way, c('Plugin.CategoryIDs') would result in an array again. The way that array is treated would have to be changed, though, since until Vanilla 2.2 it would have been `[2,4]`while with this approach it would be `[2 => true, 4 => true]` but that could be handled by a simple `$categoryIDs = array_keys(c('Plugin.CategoryIDs'))`.

Since most of the extra work has to be done when a form is saved, I guess the overhead of adding some extra code for CheckBoxList should be worth it, so that it still can be used in the configurationModule.

It would be great to get some feedback of your thoughts concerning configModule and CheckBoxList.

**Comment by linc** [comment]
Your proposed alternative behavior for CheckboxList sounds fine to me. My only question is whether the config should have a caveat for that scenario or simply always deal with arrays that way. I suspect the latter but I haven't dived into it.

**Comment by R-J** [comment]
I do not understand that question, sorry. Do you mean by "the config should have a caveat" that there should be any changes/additions made to the config class?

I don't think there is any change necessary/possible. It must be done in the configurationModule. But since I haven't taken a closer look on how this could be implemented, I'm also unsure...

**Comment by rbrahmson** [comment]
Linc - neither R_J nor yours truly understand your question ("My only question is whether the config should have a caveat for that scenario or simply always deal with arrays that way.").  

I do hope that this issue will be resolved,   
BTW, what does the "Backport" label mean?

**Comment by rbrahmson** [comment]
Linc - can you check whether this will be resolved as R_J suggested?  If not, we're both awaiting clarifications on your recent question;-)
