### ISSUE TITLE
Automatic ID incrementing does not also increment IDs in the "for" label attribute

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4190]
In /entry/login, when you click on the "Forgot?" link, the label "Enter your Email address or username" has a "for" attribute with the value "Form_Email", but the input's id is: "Form_Email1".

**Comment by charrondev** [comment]
While it may be obsoleted by the authentication refactor, the old sign-in pages will still be around for a long time.

Besides that this likely affects more forms than just this one, since we do that incrementing everywhere. I've retitle the issue to broaden the scope a bit.

**Comment by bleistivt** [comment]
> Besides that this likely affects more forms than just this one

True, the same thing happens to the category selector if you force `$PostController->CategorySelector = true;` (because the default CategoryID field turns into a hidden input when a new discussion is posted from the category view).

If the `for` attribute would also increment, it would change the API of pages like /entry/passwordrequest.
The form class would need some kind of intelligent detection to search the POST data for incremented fields.

As far as I can tell it either has to stay the way it currently is or multiple inputs with the same name on a page should be forbidden entirely and throw an exception / notice.

**Comment by charrondev** [comment]
The real fix here will happen with new forms on the frontend feeding to API endpoints instead of using `Gdn_Form`. Or strategy in new views is to generate unique IDs using `lodash/uniqueId` where we need them and pass these ID's around instead of hardcoding string IDs. You can see many examples of this in Rich Editor.

I'm afraid there's no easy fix for this though.
