### ISSUE TITLE
Accessibility & Rich Editor: Emojis alt text 

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#4296]
User of assistive technology to be able to understand emojis used in posts. 

Emoji used in posts have alt text, however they do not describe the picture - for example ":)" to be "Smiley Face"

**Comment by R-J** [comment]
One big problem is, that there is no information "Happy Face" or "Sad Face". You have the shortcut and the filename. Since the filename could be a anything, I would say that there is no solution which suits every case.

But Vanilla is built for being extensible! So with a very short addition to you themes themehooks file, you would be able to customize the format used for emojis:

~~~
public function emoji_init_handler($sender) {
    $sender->setFormat('<img class="emoji" src="%1$s" title="%2$s" alt="emoji_{basename}" height="20" />');
}
~~~

That's all. By giving speaking filenames, you would create "emoji_smile", "emoji_open_mouth", "emoji_what_ever_the_file_is_named" as "alt" text.


You can see what placeholders are available by looking on this snippet:
~~~
        $img = str_replace(
            array('%1$s', '%2$s', '{src}', '{name}', '{dir}', '{filename}', '{basename}', '{ext}'),
            array($src, $emoji_name, $src, $emoji_name, $dir, $filename, $basename, $ext),
            $this->format
        );
~~~

**Comment by slafleche** [comment]
This will be possible in the new editor. Modern screen readers are able to read emojis. Older browsers will get alt text for emojis.

**Comment by charrondev** [comment]
Rich Editor emojis implement alt text and are native so have much better assistive technology support.
