### ISSUE TITLE
Show some kind of indication why a user was banned

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4518]
When a user is banned, we should add the details of the ban into user attributes and think of a way to display them. Details include the reason for the ban, the offending record, whether it can be reversed, etc.

**Comment by DaazKu** [comment]
If Warnings & Notes is ON we should definitely put a note with all the details.
Otherwise the details of the last ban stored in the user's attributes is OK I guess.

**Comment by DaazKu** [comment]
I started by checking how the banning model was working and started to plan how we would put some kind of message/feedback for the bans.

When I started testing how everything currently works I found out that this issue seems to have been implemented/fixed:

![screen shot 2017-06-27 at 2 47 14 pm](https://user-images.githubusercontent.com/2412909/27604547-92ef4f34-5b47-11e7-8189-726da5a72cb4.png)

https://github.com/vanilla/vanilla/pull/5275 Added a functionality to find the ban rules affecting a given user:

![screen shot 2017-06-27 at 3 17 56 pm](https://user-images.githubusercontent.com/2412909/27605841-e0359c7c-5b4b-11e7-80e0-ea41ef3ba404.png)

![screen shot 2017-06-27 at 3 19 01 pm](https://user-images.githubusercontent.com/2412909/27605868-fbe82412-5b4b-11e7-8414-79dde21b9885.png)

- Banned by a community manager is a ON/OFF situation.
- The warning and notes bans have their own history

I found out some bugs that are corrected by https://github.com/vanilla/vanilla/pull/5699
