### ISSUE TITLE
In-page comment anchors can be moved by other content loading in the page

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4695]
If you're linking to a specific comment in a thread and, say, an embedded tweet is included higher in the page, you'll likely end up in the wrong place.  The document loads and the browser drops to the proper position on the page, before the embedded content loads and pushes everything below it further down the page.

**Comment by linc** [comment]
This is unlikely to have a short-term solution.

**Comment by bleistivt** [comment]
A :target selector could be added to the default stylesheet to make it easier for users to see which post is referenced by the location hash.

Example on this github page:
https://github.com/vanilla/vanilla/issues/4695#issue-184075535

Is there a standard highlight color? `#FFFF99` would be consistent with the fading highlight effect present when ajax content is inserted. But it was never standard, I guess, since I just copied that over from jQuery UI back then.

https://github.com/vanilla/vanilla/blob/2e6cbc76c3d9ff3bde94e01938ca93458f4a4bf5/applications/dashboard/design/style.css#L5967-L5983

If this breaks too many themes, it should definitely be considered for the new default theme.

**Comment by charrondev** [comment]
That in particular is a tough change to introduce in an  existing theme because our existing themes are not variable driven. Because of that we have no good way to introduce things with colours without clashing with a bunch of existing sites. Definitely something to consider for the next theme revision.

**Comment by bleistivt** [comment]
I still think this is relevant. Most web applications do some kind of permalink highlighting.

**Comment by charrondev** [comment]
@bleistivt I agree. This has been a pet peave of mine for a little while, and is something we're taking into consideration with an upcoming new base theme.

**Comment by bleistivt** [comment]
Still relevant.

**Comment by bleistivt** [comment]
Still relevant.
