### ISSUE TITLE
Improper IP address for users inserted via 'Not Spam'

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4952]
Marking a Registration entry in the spam queue as 'Not Spam' will insert the registrant into the user table with the Latest IP being that of the approver's. The IP value should be the IP that the registrant tried registering with.

**Comment by topcheese13** [comment]
The only possible "quick fix" I see is passing an option to the insertForBasic method of the userModel when we call it from the logModel, 
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.logmodel.php#L787

an option saying we are restoring a user marked as spam. This way we could set the variables (DateFirstVisit, DateLastActive, LastIpAddress) to the correct values after the addInsertFields function has been called in the insertForBasic. 
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermodel.php#L2842

InsertIPAddress would remain the same, the user doing the not spam operation should be the insert user, which means his IP would be the InsertIP.

**Comment by DaazKu** [comment]
I think that the core of the problem here is that addInsertFields has been wrongly update to add DateFirstVisit, DateLastActive and LastIpAddress.

From Gdn_Model:
```
    /**
     * Adds $this->InsertUserID and $this->DateInserted fields to an associative
     * array of fieldname/values if those fields exist on the table being
     * inserted.
     *
     * @param array $Fields The array of fields to add the values to.
     */
    protected function addInsertFields(&$Fields) {
```

DateFirstVisit, DateLastActive and LastIpAddress are not insert fields. They are fields that need to be set when we create a user record. We should move these out from addInsertFields and refactor the code accordingly.
