### ISSUE TITLE
Basic registration can return a truthy value instead of a UserID if a registration is tagged as spam

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4993]
"User REDIRECT_APPROVE not found"

https://github.com/vanilla/vanilla/blob/b72775089f28926e4974f6ad9da70427779c8964/applications/dashboard/models/class.usermodel.php

Long story short insertForBasic can return the string "REDIRECT_APPROVE" as a value.
Most of the code assume that insertForBasic will return an UserID or false which is not the case!

**Comment by initvector** [comment]
I cannot recreate this issue using "regular" registration, as mentioned in the original user-submitted issue.

`UserModel::insertForBasic` can return `UserModel::REDIRECT_APPROVE` ("REDIRECT_APPROVE") if the values being inserted trigger a positive match during the SPAM check.

`UserModel::insertForBasic` is only directly called three places in core Vanilla:

1. `UserModel::register` - Used for the "captcha" and "basic" registration types.
1. `UserModel::register` - Used for the default registration type.
1. `LogModel::restoreOne` - Used when inserting a user record from the log table.

The only non-SSO area where `UserModel::REDIRECT_APPROVE` should be bubbling up is in `EntryController::registerBasic`, which already has a condition for that specific value:

```php
if ($AuthUserID == UserModel::REDIRECT_APPROVE) {
    $this->Form->setFormValue('Target', '/entry/registerthanks');
    $this->_setRedirect();
    return;
}
```

There is already an [SSO issue related to SPAM registrations](https://github.com/vanilla/vanilla/issues/4991), so maybe they're related. I'll test for this behavior there too.

Since I cannot recreate the issue and am unable to immediately see any way the cited result can be returned in Vanilla's current codebase, I'm going to close this issue. I'm cautiously optimistic this behavior may've been addressed in the six weeks since it was originally filed. If that optimism is unwarranted, we can revisit.
