### ISSUE TITLE
Catgory deletion: Add (another) confirmation step

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5037]
If a category is to be deleted and no replacement selected, add a second confirmation page that lists:

* How many discussions will be destroyed by this action. Specify there will be no saving them via the Change Log.
* What categories will be destroyed by this action, including any subcategories.

See #4992 and base this off of that change.

**Comment by DaazKu** [comment]
I was thinking of doing this instead of another confirmation page:
- Disabling the proceed button.
- Add a delete everything option.
- Make the user choose (radio buttons) between move or delete everything.
  - For option 1 -> Show the replacement category dropdown and enable proceed button.
  - For option 2 -> Show the warnings cited in this PR's description and add an additional checkbox to enable the proceed button.

**Comment by linc** [comment]
As long as the full scope of the deletion is made clear, I'm fine with it.
