### ISSUE TITLE
Mentions: Usernames containing '@' break (via SSO, imports)

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5077]
Usernames with the @ are split in two even if double quoted. 
Double quotes are not escaped and also break mentions

**Comment by charrondev** [comment]
I don't think there's really any good way to do this. There needs to be a way to know where to start in a string like `My email is adam@charrondev.com. @DaazKu did you know this?`.

If we were to allow `@` symbol in usernames there would be no way to know which one to start at.

**Comment by charrondev** [comment]
I'm recategorizing this a little. This is 100% Won't Fix for Advanced Editor though. It's possible for us to make this work out for Rich Editor though, if we can clearly define the constraints for what is allowed in a username. At that point in time, SSO implementations and migrations would need to validate the usernames as they come in, or deal with mentions not working, because there just isn't a single solution that covers every single use case.

Our current system always registers `@` as a symbol to start a new mention. We could probably make this a little better be changing that starting sequence to be ` @` instead, but that would then restrict that character sequence.
