### ISSUE TITLE
Restoring spam-blocked comment should update latest comment as appropriate

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5238]
If a comment restored from the log is the latest comment in a discussion, the latest comment info should update as well.

**Comment by DaazKu** [comment]
I am tempted to use [CommentModel::updateCommentCount()](https://github.com/vanilla/vanilla/blob/46b1029df847cd5885a21ba90d2bb3519f6e98f5/applications/vanilla/models/class.commentmodel.php#L1202) here instead of adding more complexity to [LogModel::recalculate()](https://github.com/vanilla/vanilla/blob/e9c5fdf1198289dd80c50259ad5d711afbe476e0/applications/dashboard/models/class.logmodel.php#L572)
