### ISSUE TITLE
Polish new discussion category dropdown for Ideas/Questions

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5337]
-You can currently create discussions in idea categories if you make your thread from the Recent Discussions page and select the category with the drop down. This shouldn't be the case. 

-If you create an Idea from the recent discussion page via the button: 
![image](https://cloud.githubusercontent.com/assets/7501633/24119306/afa13348-0d7e-11e7-8773-d826235d780b.png)

It successfully isolates your idea category and only displays that as an option in the category dropdown. Most Q&A users also want this option for questions.

**Comment by linc** [comment]
This needs a generic system that our "discussion type" plugins then use in a consistent way.

**Comment by initvector** [comment]
I've added filtering to the category dropdown, based on the allowed discussion types for a category, This is the same type of indicator used by the new discussion button to determine what options should be available.

The ease of posting discussions in an Ideation category should be fixed with this update. However, if we're going to use it for limiting posting for questions or polls, it will need to be done in their respective addons.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5785
