### ISSUE TITLE
[TravisCI] Investigation - Round 2

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5472]
See [the main issue](https://github.com/vanilla/vanilla/issues/5470)!

**Comment by initvector** [comment]
I can't get the build to fail any more, but here's what I was able to uncover while looking into this:

As has already been reported, when the build is falling with the "Vanilla did not install" error, it's because the site's config erroneously has its `Garden.Installed` config set to true. This seems to be happening around this call to [APIv0::saveConfig](https://github.com/vanilla/vanilla/blob/baa284ea1d9926fad9fd8041a5f31823e9854690/tests/APIv0/APIv0.php#L185). During a failure, before this call, the config is empty. After this call, the config is fully populated, complete with `Garden.Installed`.

The irregularity of the issue lends credence to this being a race condition/concurrency issue.
