### ISSUE TITLE
Vanilla 2.4 cannot be installed as is on apache

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5709]
We redirect to `/dashboard/setup` when vanilla is not installed.
From there we ask if we need to install an `.htaccess` or not. That file handles the requests rewrite on apache.
The problem is that `/dashboard/setup` needs to be rewritten otherwise you get a 404.

We need to update our installation documentation to make users rename `.htaccess.dist` to `.htaccess`
We should also remove the `.htaccess` option from the setup. (Don't forget to update the unit tests)

**Comment by DaazKu** [comment]
@initvector @linc What do we do here? Do we ditch the whole copy htaccess feature in setup and update the doc to say that the content of .htaccess.dist needs to be copied in .htaccess for vanilla to work?

**Comment by initvector** [comment]
Apache should still work with passing path info (e.g. /index.php/dashboard/setup) when .htaccess isn't present. Do you anticipate it being difficult for Vanilla to determine if it should prepend requests with index.php as needed (e.g. if "pretty URLs" aren't available)?

**Comment by DaazKu** [comment]
Pretty URL is now ON and assumed to be working by default.
Starting to make exceptions to make the setup work is not the way I would go.
BY Clarifying the installation process and stating what needs to be done, like for nginx, the problem will be fixed.

**Comment by DaazKu** [comment]
Hitting /index.php/dashboard/setup does work but the URLs are made using the prettyUrl syntax internally.

**Comment by tburry** [comment]
Gdn_Request should construct the proper URL. Did we remove the check for X_REWRITE?

**Comment by DaazKu** [comment]
Apache has no rewrite by default so /index/dashboard/setup is never routed to index.php that's the whole problem here.

**Comment by tburry** [comment]
Right, but that's not what I said. Gdn_Request looks for X_REWRITE and if it's not there then returns differently formatted URLs from Gdn_Request->url(). I'm asking if that was removed.

**Comment by DaazKu** [comment]
No it was not removed.
But it doesn't matter. [We default to $rewrite being on now](https://github.com/vanilla/vanilla/blob/c1214664d1794bc3741ddd78d815924cf27038d1/library/core/class.request.php#L1421).

**Comment by DaazKu** [comment]
I thought we wanted to get rid of using the p parameters.
If I'm not wrong we should just update the installation documentation and so that people can setup their redirects pre-installation.

**Comment by tburry** [comment]
As per our offline discussion plus a few thoughts. I think we can take the following course:

1. Default the rewrite setting to false instead of true as it used to be. This will fix the bug.
2. We should consider making URLs that don't have X_REWITE be in the format index.php/path rather than index.php?p=path. This will allow us to remove a lot of logic that concatenates a query string to a path and head off a lot of bugs.
3. I really don't think we should have the config setting that forces a rewrite. It should also be the server variable. Since this could break installations this is something we shouldn't really do until we have some sort of diagnostics page which is not in the works right now.
4. Eventually we want to prevent installations without X_REWRITE which will mean updating the installation process. This can wait until we move to our newer APIv2 install endpoint. It has a check requirements endpoint that can have the X_REWRITE check too.
