### ISSUE TITLE
Prompt for password when changing email address

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5805]
The most sensitive action a (non-privileged) logged-in user can make is to change their email address. This is because it could be made maliciously on an open login and hand control of the account to another party immediately. The minimal improvement that would sidestep this issue is to prompt for password before allowing the changing of email.

On accounts connected over SSO this is a far less critical issue because email is typically synced over said connection and it's uncommon that the email is even made editable. In my opinion, we should omit this protection for SSO-connected accounts to sidestep the issue of reauthentication. I think it would be prudent to detect whether a valid password hash is set and only if it is, proceed with this extra prompt.

Please consider whether there are holes in this plan or other interactions that could complicate this before investing in a solution.

**Comment by R-J** [comment]
I have one remark and one wish concerning that:

**The remark:** I think there might be more critical information in the user profile which should be secured with a password request. Maybe the connected social accounts or some additional fields added with the profile extender. The implementation shouldn't be hard coded to the password request.
I think it would make sense to make this a popup which should be available from anywhere in the ProfileController.

**The wish:** could you please implement it with an event that offers a "Handled" EventArgument?

I was thinking about a plugin which offers "password-less" login by mail: instead of entering username/password combination, a user can enter his mail and request a log in link which, when clicked, logs the user in as the user connected to the mail account.

A user who is using that already on registration wouldn't know his password and therefore I would have to bypass the method you plan to implement.

**Comment by DaazKu** [comment]
We actually don't want to check if SSO is ON or not. We should just set if the user has a password set on his account. i.e. if a user has the HashMethod set to random we should not ask for his password.

This would handle SSO and "password-less" users cases.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6056
