### ISSUE TITLE
Change the way Youtube embeds are done.

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5824]
Currently, we replace Youtube embeds with some HTML and then switch it to the embed iframe on click. We did this originally for speed when looking at pages with a tonne of youtube embeds. This was a good solution for the time, but causes problems now with API calls that don't know how to embed the videos.

I'd like to try switching the youtube embeds to proper Youtube videos. If we need to speed it up I think we can try instead using javascript to replace the iframe with the picture rather than vice-versa. For this change though just going with the iframe itself is good enough.

**Comment by slafleche** [comment]
Can we also wrap the iframe in a div (with a class) so we can make the iframes responsive?

**Comment by linc** [comment]
The issue here was never with 1-off embeds, but in situations where many videos are embedded into a single page. There are absolutely pages out there with 20 or even 50+ video embeds, and I don't think it's even an edge case. In that scenario, the forum page basically becomes unusable.

Can Javascript intercept an iframe before it initiate calls its source? If that's feasible we have an OK path forward, but I don't think reverting an early optimization like this will go well at all.

**Comment by Charrondev** [comment]
If an iFrame is in the page directly it will attempt to load the content of it before there is any guarantee of the javascript running as far as I can tell.

**Comment by DaazKu** [comment]
Possible solution:

```html
<iframe id="{UNIQUE_ID}" src="about:blank" />
<script>
    window.onload = function() {
        var iframe = document.getElementById("{UNIQUE_ID}").src = {URL};
    };
</script>
```

**Comment by charrondev** [comment]
@tburry This is resolved with Rich Editor. The current method in Rich Editor is:

- An HMTL link to the original video is returned with embed data JSON encoded in a `data-embed` attribute.
- Javascript mounts the Image preview & the video iframe.
