### ISSUE TITLE
[API v2] CommentApiController index "after" parameter should be changed to "from"

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5850]
The "after" parameter should be replace by to "from" parameter.
They basically do the same thing but the latter is easier to use.

You can specify `from=2017-01-01T00:00:00` and get everything from that date an greater.
Using the after you would have to do: `after=2016-12-31T23:59:59` which is complicated for nothing.

**Comment by tburry** [comment]
The use case of being able to page by passing in the date of the last in the previous page works well with after/before.

**Comment by linc** [comment]
I agree with @DaazKu; using a `from` of the actual datetime instead of an `after` of -1 (second/minute/day) from the datetime is easier to use.

It's better to have a clearly communicated parameter than a programmatically convenient one when the two are in conflict. We can easily do the `after` -> `from` conversion for paging. But it adds cognitive load to all the humans using the API if we use `after` instead of `from`.

**Comment by DaazKu** [comment]
I think using the time for pagination is not a good idea because we will probably encounter the edge case where the last comment of page 1 has the same dateInserted and the first comment of page 2.
This would skip the first comment on the second page because the query will check for dateInserted > date.

We should probable use IDs instead.

**Comment by tburry** [comment]
This parameter is going to be removed because we can do `?dateInserted=[2016-11-05,2017-01-01]`
