### ISSUE TITLE
Address Conversation's participants "deleted" flag issue

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5950]
This "deleted" value means that a participant "left the conversation".
The flag's name does not reflect its current meaning.

Also note that get_participants returns every participant even if they left. Which is bizarre at first sigh. (The conversation's countParticipants does not count deleted participants)

@tburry has his view on how he wants us to address that.

**Comment by tburry** [comment]
Let's make the following changes to the API endpoints (not the DB for now).

1. Change the deleted flag to status with type: string and enum: [participating, deleted].
2. Add a status filter to get_participants for the status. A filter value of "all" will return all participants. This is a bit unfortunate because null would be better, but since we are requiring the query string a value must be inputted.
3. Make the default filter be participating.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6030
