### ISSUE TITLE
Move to PHP 7.0

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5966]
I want to start developing against PHP 7.0 sometime early 2018. This needs to be planned with the OSS releases. Can you add issues to this epic to see what needs to be done @linc?

**Comment by linc** [comment]
It's [been announced](https://open.vanillaforums.com/discussion/35686/vanilla-will-end-php-5-6-support-in-2018) PHP 5.6 support will end with 2.5. I suggest we move directly to 7.1, since official 7.0 support ends BEFORE PHP 5.6 support.

I've also updated the version checking in the Dashboard in this PR, so that 2.5.1 (upcoming) will warn users about this change: https://github.com/vanilla/vanilla/pull/6271

If there are specific core coding tasks you had in mind, I don't know what those are. From a communication perspective, I don't think we have more work to do here.

**Comment by Charrondev** [comment]
The only thing I can think of from a coding perspective is some themes' view overrides probably need some function calls fixed (to view arguments being passed which would now throw an exception).

https://github.com/vanillaforums/vanilla-clients/issues/247
