### ISSUE TITLE
Performance improvements when moving multiple categories

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5968]
When moving categories, the category tree is rebuilt after each move. If you need to move several categories, the process can take much longer than expected, because there is the delay of waiting for each request to finish as the tree is rebuilt.

Any suggestions for improving this workflow would be swell.

**Comment by DaazKu** [comment]
My take on this is that we should either:

A. Set a flag that puts the tree as dirty (instead of rebuilding it) and when requesting categories we should update the tree if the flag is set.
B. Set an option that will control whether the tree should be rebuilt when updating the parentCategoryID. The option would be set to true by default. This allows mass category update without performance penalties but also introduce a possible way to break the three if you forget to rebuild it at least one time.
C. In the long term, if we decide to handle batch requests, we could allow updating multiple categories in one shot and update the tree only after the updates.
