### ISSUE TITLE
Dashboard: Fluid fixed navigation panel is broken

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6021]
The dashboard left navigation panel used it fix itself so that it couldn't be scrolled out of view. This no longer works.

This seems to originate from  this commit: https://github.com/vanilla/vanilla/commit/56b380f31c6f9cd12e9367aac64d3e5e24777ee3#diff-bcd04ed30cdf4a89c731b25091d61891

**Comment by Charrondev** [comment]
While reverting that commit seems to restore the old behaviour, it still leaves this bug: https://github.com/vanilla/vanilla/issues/4868, which seems to be caused by the height not being recalculated correctly when the side panels are collapsed and expanded.

https://github.com/vanilla/vanilla/commit/56b380f31c6f9cd12e9367aac64d3e5e24777ee3 Seems to have resolved the issue by disabled the fluid part of fixing the panel altogether. A more granular solution will be required.

**Comment by Charrondev** [comment]
I've determined that this will require significantly more work than I had initially imagined. I'm going to table this until we have to time to rip apart some of the dashboard's javascript as even if I fixed this edge case the actual performance of the fluid fixed functionality it terrible.
