### ISSUE TITLE
Add date parser for API date parameters

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6037]
The API will need parsing for date field filters. Current requirements for the parser are:

1. Date fields should be strings.
1. The time portion is optional.
1. The date strings should provide a comparison operators.
    * Supported operator: >, >=, <, <=
    * Example: `>=2017-09-21` would be interpreted as "greater than or equal to 00:00:00 on September 21st, 2017"
    * Example: `<2017-09-21` would be interpreted as "less than 00:00:00 on September 21st, 2017"
1. Limited support for [interval notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals) needs to be implemented to support date ranges.
    * Supported operators:
        * Inclusive: [, ]
        * Exclusive: (, )
    * Example: `[2017-09-21,2017-09-22)` would be interpreted as "between 00:00:00 on September 21st, 2017 and 23:59:59 on September 21nd, 2017"

**Comment by tburry** [comment]
Also this:

The schema should represent date filters as the following data schema:

```json
{
    "type": "object",
    "properties": {
        "op": {
            "type": "string",
            "enum": ["=", ">", "<", "<=", ">=", "[]", "()", "[)", "(]"]
        },
        "value": {
            "type": "array",
            "items": {
                "type": "datetime"
            }
        }
    }
}
```

This looks like the best we can do with the current features of the schema. Ideally, the value could be a single date or an array of dates, but we don't have the ability to specify multiple types yet. We could also add support for the [maxItems](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.11) and [minItems](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.12) for arrays which would be an easier enhancement. Both these enhancements are not essential for the filter to work.

We should add a filter to the schema in order to convert strings from condensed format to the above structure.

**Comment by tburry** [comment]
Okay I've added support for multiple types and minItems and maxItems so the following schema should now work:

```json
{
    "type": "object",
    "properties": {
        "op": {
            "type": "string",
            "enum": ["=", ">", "<", "<=", ">=", "[]", "()", "[)", "(]"]
        },
        "value": {
            "type": ["datetime", "array"],
            "items": {
                "type": "datetime"
            },
            "minItems": 1,
            "maxItems": 2
        }
    }
}
```

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6123
