### ISSUE TITLE
Mentions autocomplete box doesn't dismiss when you click away from it

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6165]
If you are composing a post with an @mention, if you revisit that mention, then you tap away to type somewhere else, the autocomplete box follows you.

![editorissue](https://user-images.githubusercontent.com/31856281/33042089-a4925792-ce0e-11e7-9d96-961fdb54caa8.gif)

![mention-moving](https://user-images.githubusercontent.com/31856281/33041749-64a8cf22-ce0d-11e7-8799-dcb39e240efb.png)

**Comment by slafleche** [comment]
Still broken for me. Oddly enough, if you write: 1 line, then an @mention then 1 line, it's fixed on the first line, but not the third.

**Comment by Charrondev** [comment]
I'm going to close out this PR. This solution was going in the wrong direction. I'll detail the task a bit more and am going to punt it to next sprint.

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/6783

**Comment by charrondev** [comment]
I've been writing some passing and failing test cases for this before we fix it, but I'd like to get @tburry's opinion on this before implementing a new matcher.

I've listed out here some cases. Keep in mind these all represent the string from the start of the comment/post/etc to the current cursor position. Check off the ones that should match.

Also note that copying these out will be a PITA in the end, because to get github to not screw up the @ symbol, even inside of a code block, you need a zero-width whitespace character.

- [ ] `@​System`
- [ ] `Sometext @​System`
- [ ] `Sometext with linebreak   
            @​System`
- [ ] `@​Séche`
- [ ] `Something @​Séche`
- [ ] `@​Umuüûū`
- [ ] `@​Some,`
- [ ] `@​Some.`
- [ ] `@​Some$`
- [ ] `@​Some^`
- [ ] `@​Some(`
- [ ] `@​Some$`
- [ ] `@​Some*,`
- [ ] `@​Some+.`
- [ ] `@​Some-`
- [ ] `@​Som_,`
- [ ] `@​Some@​`
- [ ] `@​Some!`
- [ ] `@​Some~`
- [ ] `@​Some=`
- [ ] `"@​Some,`
- [ ] `"@​Some.`
- [ ] `"@​Some$`
- [ ] `"@​Some^`
- [ ] `"@​Some(`
- [ ] `"@​Some$`
- [ ] `"@​Some*,`
- [ ] `"@​Some+.`
- [ ] `"@​Some-`
- [ ] `"@​Som_,`
- [ ] `"@​Some@​`
- [ ] `"@​Some!`
- [ ] `"@​Some~`
- [ ] `"@​Some=`
- [ ] `Newline with special char
                       @​Umuüûū`
- [ ] `@​"Someon asdf `
- [ ] `@​Some ` // Single space but no closing braces?
- [ ] `@​someone with non-wrapped spaces`
- [ ] `@​"someone with a closed space"`
- [ ] `@​"Do we close on a newline?
            other text`
- [ ] `@​"What about multiple spaces?      `
