### ISSUE TITLE
'Last visit' isn't reliable

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#6476]
We've received multiple reports that users are able to re-visit a site and even post without their "Last Visit" datetime updating (`Gdn_User.DateLastActive`). This is for day+ periods of time, not the grace period (20 minutes?) on updating this value.

This also correlates to the Visits count being off (consistently low), probably for the same reason.

Latest open source discussion: https://open.vanillaforums.com/discussion/35846/user-visit-not-tracked-in-moderation-users#latest

**Comment by LauraMakesArt** [comment]
https://github.com/vanilla/support/issues/12

**Comment by initvector** [comment]
I'm getting mixed signals. The current issue says `User.DateLastActive` can be wrong, which can also cause `User.CountVisits` to be off. The referenced issue mentions `User.CountVisits` can be off, but `User.DateLastActive` seems to be consistently updating as expected. Maybe these are two separate issues. Either way, I am unable to recreate either, with or without caching enabled. That said, here's how things *should* work, based on tracing the workflow through the code:

The logic for determining whether or not a user's request is part of a new visit is in `Gdn_Session::newVisit`. It is based on a "visit" cookie that is set in a user's browser with a twenty-minute expiry.

1. If the user doesn't have the cookie when the check is run (e.g. it expired or was never set), and it's been twenty minutes since the `DateLastActive` value on their user record, it's a new visit.
1. If the cookie exists, the visit is not new.
1. If the cookie does not exist, but the user's `DateLastActive` value is within twenty minutes of the current time, the visit is not new.

Regardless of whether or not the visit is new, the visit cookie is reset to expire twenty minutes from the time of the check. This means at least a twenty-minute lull in activity is required for a new visit to be registered.

Updating a user's `DateLastActive` field is mostly managed by [`UserModel::updateVisit`](https://github.com/vanilla/vanilla/blob/061b7280bf79cfc1b2d8045aad1decc3fb36acd4/applications/dashboard/models/class.usermodel.php#L3161). In this method, `DateLastActive` is only updated if the existing value is more than five minutes old. `UserModel::updateVisit` is also the only place in core Vanilla where `Gdn_Session::newVisit` is called.

In core Vanilla, `UserModel::updateVisit` is called in three places:

1. [`Gdn_Statistics::tick`](https://github.com/vanilla/vanilla/blob/061b7280bf79cfc1b2d8045aad1decc3fb36acd4/library/core/class.statistics.php#L747) - Called by client-side JavaScript on each page load for analytics purposes (/settings/analyticstick.json).
1. [`Gdn_Session::start`](https://github.com/vanilla/vanilla/blob/061b7280bf79cfc1b2d8045aad1decc3fb36acd4/library/core/class.session.php#L463) - Called in a lot of places. Also called on every request. However, `UserModel::updateVisit` is only invoked if we're setting the identity for the current user, which typically only happens during sign-in.
1. [`Gdn_PasswordAuthenticator::authenticate`](https://github.com/vanilla/vanilla/blob/061b7280bf79cfc1b2d8045aad1decc3fb36acd4/library/core/authenticators/class.passwordauthenticator.php#L89) - Called when signing into Vanilla with a password (e.g. /entry/password).

If caching is enabled on a site, user records are cached for up to an hour. Outdated user information (including activity/visit info) should still be updated by `UserModel::updateVisit` making a call to `UserModel::setField`, [which updates cached rows.](https://github.com/vanilla/vanilla/blob/061b7280bf79cfc1b2d8045aad1decc3fb36acd4/applications/dashboard/models/class.usermodel.php#L4638)

Based on initial review, it appears regularly updating a user's visit/activity information is heavily dependent on background calls to /settings/analyticstick.json. If the user's browser is blocking these calls, or if there is conflicting/broken JavaScript on the page preventing the request from being sent, it would likely prevent the aforementioned fields from being updated without a new sign-in. This can also be the case if the `Garden.Analytics.Enabled` config is set to false, because the client-side "tick" request would not be made. If `DateLastActive` is being updated, but `CountVisits` is not, it may indicate the "visit" cookie is not being unset when it should be.

This is more speculation than anything, but it may also be possible that an addon (or some part of core Vanilla that isn't jumping out at me) could be adjusting `DateLastActive` before  `UserModel::updateVisit` or `Gdn_Session::newVisit` are called. Since these methods rely on `DateLastActive` being outside a relative timeframe to trigger a new visit, if the value were updated before these methods were run, it would prevent `CountVisits` from being updated.

**Comment by DaazKu** [comment]
- DateLastActive is updated when
  - You start a new session
  - settings/analyticsTick.json is called and you have not been active for 5 minutes. As Ryan pointed out there are multiple reason why this would not fire on page load:
     - Javascript error on the page
     - Ad blockers preventing that particular call from executing
     - Garden.Analytics.Enabled set to false
     - The forum running on a ["localhost setup"](https://github.com/vanilla/vanilla/blob/f30141c503422b84040c26463fffa18c0ea3a4c5/library/core/class.statistics.php#L241) with Garden.Analytics.AllowLocal not set to true.

- CountVisits is updated when
  - You start a new session
  - settings/analyticsTick.json is called and you do not have the visit cookie set and your DateLastVisit is older than 20 minutes.
  
There's a bug with VanillaAnalytics that prevents CountVisits from being updated.

[newVisit()](https://github.com/vanilla/vanilla/blob/6ec4d91cc4a8b71824904b9c2ebd1b8b9536eeb5/library/core/class.session.php#L287) is called from [AnalyticsTracker::trackingIDs()](https://github.com/vanilla/analytics/blob/08311b2482be5343b9125ca9e3998d0438d98027/plugins/vanillaanalytics/models/class.analyticstracker.php#L330) which is called in multiple place.

Each call to `newVisit()` update the visit cookie expiration by 20 minutes. Since CountVisits is actually incremented by ajax calls this mean that any call to newVisit() in the system prior to that ajax call will effectively prevent CountVisits from being updated.

The 2 most problematic places are [Gdn_session_start_handler](https://github.com/vanilla/vanilla/blob/6ec4d91cc4a8b71824904b9c2ebd1b8b9536eeb5/library/core/class.session.php#L452) which is executed just before the update visit call in Session::start(),
and [base_render_before](https://github.com/vanilla/analytics/blob/08311b2482be5343b9125ca9e3998d0438d98027/plugins/vanillaanalytics/class.vanillaanalytics.plugin.php#L94) which is executed on every page load.

**Comment by DaazKu** [comment]
To make sure that DateLastActive and CountVisits are updated I would suggest that we move these updates out of /settings/analyticsTick.json since it is unreliable for the reason listed above.

We should create a isNewVisit() function that would not update the cookie and use that in Analytics.
Updating the newVisit() DocBlock would also be a good idea.

**Comment by DaazKu** [comment]
@linc @LauraMakesArt @initvector Can we close this?
