### ISSUE TITLE
Rich Editor - Non-native emoji support

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6531]
We'll need to do testing to see how good the emoji support it across browsers and devices. From what I've seen, emoji support is really good, but I'm not 100% sure the older browsers have "all" of the emojis.

**Comment by Charrondev** [comment]
Emojis are a combination of browser support and OS support.

http://caniemoji.com/microsoft-windows/ Windows is the place where compatibility is kind of iffy. To work in chrome on windows 7 and 8, we'll need image fallbacks, which the onesignal library I provided supports.

Since we probably will need to support this, it might be a good idea to fork the OneSignal library and make whatever accessibility changes we need to it. It is restricted to a smaller subset of unicode, and has image fallbacks in the form of spritesheets for all of them.

**Comment by slafleche** [comment]
This library looks like a great option for backwards compatibility:
https://github.com/twitter/twemoji

**Comment by slafleche** [comment]
Closes: https://github.com/vanilla/vanilla/pull/6644
