### ISSUE TITLE
Changing cache folder to path outside forum root will fail

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#6798]
A [user reported](https://open.vanillaforums.com/discussion/36058/tmp-being-filled-with-files-called-atomic) that his /tmp folder is flooded with Vanilla files and showed an extract of a cached theme file.
He hasn't responded by now but I assume he uses /tmp as his cache folder.

When looking at the sources I found one hardcoded "/cache" appearance ([PR already created(https://github.com/vanilla/vanilla/pull/6797)). At first I thought that this might be the problem, but this method seems not to be used anywhere.

The problem could be in AddonManager->setCacheDir which already states "If this doesn't include **PATH_ROOT** then it will be prepended."
Obviously this will "fail" for anyone trying to use `/tmp`. This might be intended behaviour, but I would recommend to change either this or the passage in the constants.php file:

~~~
// If you want to change where these paths are located on your server, edit these constants.
if (!defined('PATH_CACHE')) {
    define('PATH_CACHE', PATH_ROOT.'/cache');
}
~~~

**Comment by charrondev** [comment]
Interesting related issue from infra. https://github.com/vanilla/dev-inter-ops

**Comment by x00** [comment]
`setCacheDir` clearly does not allow for the cache folder to be outside PATH_ROOT or it will append path root to it.  This will cause insentiences. 
```
    public function setCacheDir($cacheDir) {
        if ($cacheDir !== null && strpos($cacheDir, PATH_ROOT) !== 0) {
            $cacheDir = PATH_ROOT.$cacheDir;
        }
        $this->cacheDir = $cacheDir;
        return $this;
    }
```

**Comment by x00** [comment]
`setCacheDir` clearly does not allow for the cache folder to be outside PATH_ROOT or it will append path root to it.  This will cause issue, on scalable setup, when you have to give location outside of the forum directory.  Also becuase there is inconsistency you can't just symlink an hope for the best. 
```
    public function setCacheDir($cacheDir) {
        if ($cacheDir !== null && strpos($cacheDir, PATH_ROOT) !== 0) {
            $cacheDir = PATH_ROOT.$cacheDir;
        }
        $this->cacheDir = $cacheDir;
        return $this;
    }
```

**Comment by x00** [comment]
If you are using boostap.before.php to route config/cache on a milt-tenant setup you can't use symlinks, especially if you want to keep data separate, which cna be a security requirement.

**Comment by x00** [comment]
If you are using bootstap.before.php to route config/cache on a milt-tenant setup you can't use symlinks, especially if you want to keep data separate, which can be a security requirement.

**Comment by x00** [comment]
give that constants.php already defines PATH_CACHE absolutely
```
if (!defined('PATH_CACHE')) {
    define('PATH_CACHE', PATH_ROOT.'/cache');
}
```

I don't see the need for PATH_ROOT it to be appended again in `setCacheDir` this use of relative path, is cargo-cult.

**Comment by x00** [comment]
PATH_CACHE should be explicitly set or not at all.

**Comment by charrondev** [comment]
That makes sense. I would accept a PR making this more flexible. Anything touching these directories would also need some off from our infrastructure team, but I can arrange that review.

**Comment by x00** [comment]
my PR would be removing

```
        if ($cacheDir !== null && strpos($cacheDir, PATH_ROOT) !== 0) {
            $cacheDir = PATH_ROOT.$cacheDir;
        }
```

There isn't really a way to detect if you want it be relative. I don't know what how hosted sit does its multi-tenancy, but absolute path make sense and is i how I recommend doing multi-tenancy. There is no ambiguity there.

**Comment by charrondev** [comment]
That seems reasonable to me. I don't think it would cause any issues.

**Comment by alex-mtl** [comment]
I am not sure if we need any change in code base.
I was successfully auto created the cache folder outside the PATH_ROOT on my localhost simply by:
```
define('PATH_CACHE', PATH_ROOT.'../../cacheXXX');
```

**Comment by x00** [comment]
for security reasons, i cannot use this syntax.

Also why is the default relative?, when this isn't how it is being applied.

**Comment by alex-mtl** [comment]
> why is the default relative?
the only reason is backward compatibility. 
(We have what we have. There are big number of existing installations which can pull changes when merged)

**Comment by x00** [comment]
> > why is the default relative?
> 
> the only reason is backward compatibility.
> (We have what we have. There are big number of existing installations which can pull changes when merged)

As i explained when this code was written it broke compatibility. 

I have been a developer on this platform for 10+ years, it is become increasing difficult to justify using the platform for clients when a needless breaking change like this can be introduced for no good reason. Then backwards comparability is used for a reason why it can't be fixed.

**Comment by x00** [comment]
if you can set the absolute path of the uploads folder, you should be able to set if for the 

because the absolute path setting is used in the framework and this code only applies to some of what the framework uses, this is obvious mistake.

**Comment by charrondev** [comment]
I'm just trying to make our position clear here. 

**On the process**

The code you're trying to change has been there for > 2 years and has been in the last few open source release.

We've recently [switched to using semver for versioning Vanilla releases](https://open.vanillaforums.com/discussion/36986/moving-to-semantic-versioning-in-2019).

2 days ago I put out a [release candidate](https://open.vanillaforums.com/discussion/37258/vanilla-3-0-release-candidate-call-for-testers#latest) of the 3.0 release. A breaking change, with some clear indication of what was breaking.

I don't intend to put out another breaking change for at least a year.

We have more stringent requirements at this point about backwards compatibility, specifically because of backwards compatibility issues in the past. If you want to make this change, _**it will have to be in a backwards compatible manner.**_

**Comment by x00** [comment]
The method is used in the boostrap/setup of the framework, how exactly would defining a new method an updating the setup to reflect it or changing the default , not be breaking to the small number of case where people are using relative path, and most likely only using ../.. paths because you give them no other option. 

It is breaking no matter what. 

This code may be 2 year old, but not as a OS release. It is has only recently broken multi-tenancy setups here.

**Comment by x00** [comment]
https://github.com/vanilla/vanilla/pull/8772
