### ISSUE TITLE
/media/scrape endpoint does not return proper aspect ratio for youtube videos

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6873]
The following videos all return incorrect ratios (seems to default to something that simplifies to 4:3)

- https://www.youtube.com/watch?v=eZTaNLfxTRU
- https://www.youtube.com/watch?v=NdiU_R71AdU
- https://www.youtube.com/watch?v=iK1R4v0LzAU

**Comment by DaazKu** [comment]
The returned ratio is the ratio of the thumbnail.

https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=eZTaNLfxTRU
```json
{
  "html": "<iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/eZTaNLfxTRU?feature=oembed\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>",
  "author_name": "lol Valley",
  "width": 480,
  "provider_name": "YouTube",
  "thumbnail_url": "https://i.ytimg.com/vi/eZTaNLfxTRU/hqdefault.jpg",
  "thumbnail_width": 480,
  "thumbnail_height": 360,
  "version": "1.0",
  "title": "Anton Died So We Could Live! - Silicon Valley",
  "provider_url": "https://www.youtube.com/",
  "type": "video",
  "height": 270,
  "author_url": "https://www.youtube.com/channel/UCfRKvxo-2oSKNptUqbciuIw"
}
```

**Comment by charrondev** [comment]
We should be using the width and height in this case then. The black bars on the thumbnail will get cropped out of the design.

The ratio of the thumbnail is essentially useless for our video embeds.

**Comment by initvector** [comment]
We could use width/height instead of thumbnail_width/thumbnail_height, but I don't want to lose those fields. They might be "essentially useless" for what we're doing with embeds, specifically, but I can see them being useful for other types of video embed implementations.

We could move the thumbnail_width/thumbnail_height (or the video's width/height) values under the "attributes" key on the response.

**Comment by DaazKu** [comment]
I think that for video/sound types we should have a "thumbnail" section. In attributes or not.
