### ISSUE TITLE
/media/scrape issues with some sites

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6874]
## Getty images

Maybe I'm missing something here, but if I grab one of their urls when I click embed on their site I see `http://www.gettyimages.ca/detail/924467776` I get back

```json
{
    "url": "http://www.gettyimages.ca/detail/924467776",
    "type": "site",
    "name": "Access Denied",
    "body": " Reference #18.cf2bf648.1522243558.3da4240f ",
    "photoUrl": null,
    "height": null,
    "width": null,
    "attributes": []
}
```

I'm thinking this should at least be an error right?

What type of URL is supposed to trigger a getty images embed?

**Comment by charrondev** [comment]
Smashcast doesn't return a proper image url for the embed. Instead it returns the Smashcast logo.

`https://www.smashcast.tv/ooghostinthemachineoo`

**photoUrl**

![](https://static.smashcast.tv/img/1a242d3a6f5d4397c5bed4dd7ba458b9.jpg)

Additionally Smashcasts embed url isn't being returned. The expected embed URL is `https://www.smashcast.tv/embed/ooghostinthemachineoo`

https://help.smashcast.tv/customer/en/portal/articles/2780310-how-can-i-embed-my-stream-and-chat-onto-another-website-

**Comment by charrondev** [comment]
## Soundcloud

https://soundcloud.com/scumgang6ix9ine/billy

This return the same URL but the expected URL is the embeddable one.

https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/scumgang6ix9ine/billy&color=ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false

**Comment by initvector** [comment]
I think there's some confusion on what /media/scrape should be doing. Is it supposed to be scraping an arbitrary URL for info, with some special handling for certain sites, or is it solely supposed to be used for prepping an embed? Several of these issues cite the wrong URL being returned (the original one, instead of a specific embeddable URL), but the original spec for /media/scrape explicitly states the same value for the input URL parameter should be returned under this key.

**Comment by charrondev** [comment]
Point taken. I think it was a misunderstanding on my part. I'm going to remove that from this issue.
