### ISSUE TITLE
Devise a plan about how to transition from /entry/connect to /authenticate

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#7205]
Meet with Todd to have all the necessary requirements.

Likely requirements:
- Allow all current SSO plugins to still work with /entry/connect
- Have the possibility of having new SSO plugins work on /entry/connect
- Make sure that all existing SSO plugins can work with /authenticate

**Comment by cdepage** [comment]
One of the biggest wins I have come across when implementing microservice architecture was ensuring a consistent and predictable data format BETWEEN services. The issue you allude to above sounds suspiciously like the same problem.
Do we have:
- a clear understanding of what data is required for each?
- a consistent methodology/format to return error condition data?
- a consistent methodology/format to return success condition data?

Can we make a consistent data payload format (e.g. the "part between the endpoints") so that these can be seamless? Assuming can't, is there the potential to put in a proper OOP facade or adapter pattern to encapsulate the data versioning and allow elegant extension when new behaviours are needed (such as the new browser-based authentication now available in Chrome)?

**Comment by DaazKu** [comment]
So, my fault here for the lack of basic context, the problem here is about migrating SSO providers data created from the old plugins so that they work properly with the matching Authenticator class.

It is not between communication between 2 services or system.

**Comment by DaazKu** [comment]
I feel like the best way to go about this would probably be to:

- Have a config to switch from the old UI to the new UI.
- Create a new column in `GDN_UserAuthenticationProvider` that allows to distinguish between old providers / authenticators so that the old plugins don't put authenticators in the old UI by mistake.
- Create new plugins that work only with the new UI. This means implementing the Authenticator class and adding hooks in the plugins to show a UI in the dashboard. (That's it)
    - These new plugins would have a feature that tries to import old providers data and convert it to the authenticator's format.

Clients will then be able to test the new plugins in the new UI and once everything works properly we can switch the config.

* Note that for client SSO plugins that are tightly coupled to `/entry/connect` it is possible to create a `ShimAuthenticator` so that they are listed in `/authenticate` but work over `/entry`. The only downside is that if they have to link a user they will have to use the old UI though.

**Comment by DaazKu** [comment]
1. Have a config to switch from the old UI to the new UI.
1. New plugins (Authenticator) needs to works with old UI
1. AutoConversion either in the authenticator itself in or in the plugin depending on which is easier.
1. Create a drop in replacement for Gdn_Form->Simple()/ConfigurationModule if needed. That way we can replace these so that the form still works.

**Comment by DaazKu** [comment]
I created a follow up issue: https://github.com/vanilla/vanilla/issues/6669
