### ISSUE TITLE
Cannot enable Applications on Windows/XAMPP

### ISSUE THREAD

**Issue by whu606** [vanilla/vanilla#7263]
Windows/XAMPP

After resolving issue of Vanilla plugin not being enabled (https://github.com/vanilla/vanilla/issues/7262) cannot enable Vanilla applications.

In Dashboard, the slider moves across and the setting is written to conf.php

![01](https://user-images.githubusercontent.com/5166805/40585231-a74e9666-61b7-11e8-8edf-e79fe500e1a6.GIF)

// EnabledApplications
$Configuration['EnabledApplications']['Vanilla'] = '/applications/vanilla';
$Configuration['EnabledApplications']['Conversations'] = '/applications/conversations';

However, the application (e.g. conversations) doesn't work, returning a 'Page not found' message if the envelope icon is clicked.

Returning to the Dashboard, the slider is reset to off, seemingly ignoring the conf.php setting:

![02](https://user-images.githubusercontent.com/5166805/40585248-0bd61672-61b8-11e8-83f8-7ae7feace9f7.GIF)

**Comment by whu606** [comment]
This issue persists in 2.6.1

**Comment by whu606** [comment]
This persists into 2.8 as does #7262

**Comment by charrondev** [comment]
I'm recognizing this as a bug, but we don't have a single internal developer running windows, and I'm not sure who would run it on production, so this is going to come purely down to someone motivated enough to do it.

I've done Vanilla installs on windows, but did not encounter this problem, likely because I was using the Window/Linux Subsystem w/ nginx instead of XAMPP.
