### ISSUE TITLE
Fix XSS In External Embeds (in editor, client js)

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#7268]
Post the following as Body:
```json
[{
    "insert": {
        "embed-external": {
            "url": "javascript:alert(/xss/.source)",
            "type": "link",
            "name": "Example Domain",
            "body": "This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.",
            "photoUrl": "javascript:alert(/xss/.source)",
            "height": null,
            "width": null,
            "attributes": []
        }
    }
}, {
    "attributes": {
        "link": "javascript:alert(/xss/.source)"
    },
    "insert": "http://www.example.com"
}, {
    "insert": "\n\n"
}]
":"\n\n"}]
```

![screen shot 2018-05-28 at 3 29 44 pm](https://user-images.githubusercontent.com/2412909/40627428-ffd3f238-628c-11e8-9568-9520492df0a3.png)

**Comment by DaazKu** [comment]
BONUS
----
Related: https://github.com/vanilla/vanilla-patches/issues/264

```
[{
    "insert": {
        "embed-external": {
            "url": "javascript:alert(/xss/.source)",
            "type": "link",
            "name": "Example Domain",
            "body": "This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.",
            "photoUrl": "https://httpbin.org/basic-auth/user/passwd",
            "height": null,
            "width": null,
            "attributes": []
        }
    }
},, {
    "insert": "\n\n"
}]
":"\n\n"}]
```

**Comment by charrondev** [comment]
Additionally the body wasn't being sanitized at all in the editor.

```json
[
    {
        "insert": {
            "embed-external": {
                "data": {
                    "url": "javascript:alert(/xss/.source)",
                    "type": "link",
                    "name": "Example Domain",
                    "body":
                        "<script>alert('Gotchya!!')</script>This domain is established to be used for illustrative examples in documents. You may use this\n    domain in examples without prior coordination or asking for permission.",
                    "photoUrl": "javascript:alert(/xss/.source)",
                    "height": null,
                    "width": null,
                    "attributes": []
                },
                "loaderData": { "type": "link", "url": "http://test.com" }
            }
        }
    },
    { "attributes": { "link": "about:blank" }, "insert": "http://www.example.com" },
    { "insert": "\n\n" }
]
```

This inserts an actual script tag in content editable. Chrome seems to prevent it from running, but thats still an issue.

**Comment by charrondev** [comment]
At its root there are 2 issues:

1. Standard html escaping XSS in the browser for an in editor portion of the rendered output. This can be worked around  by replacing most embeds (that we created the HTML for) with react templates.
2. We are not sanitizing any urls anywhere period. We need to be validating url schemes (only allow https:// and http://).

Our current sanitization scheme handles this by prepending `javascript:` url schemes with `denied:`. So `javascript:alert(/xss/.source)` would become `denied:javascript:alert(/xss/.source)`.

For this we can add a function `sanitizeUrl`, that will restrict url schemes to a whitelist. We will need to devise a similar method for the client. The `SanitizeTest` should be enhanced so that we do not miss testing of a blot or embed.

As I see it there are 3 types of sanitization that we need to potentially perform.

1. Generally HTML contents.
- Needs `htmlspecialchars`.
2. Urls
- Needs `sanitizeUrl`.
- Needs `htmlspecialchars`.
3. CSS URL contents.
- Needs `sanitizeUrl`.
- Needs `cssSpecialChars`.
- Needs `htmlspecialchars`.

@DaazKu Does that seem  sufficient to you?
