### ISSUE TITLE
Editor: File upload fails when AllowedFileExtension is not added to mimetypes

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7270]
## Details

Whenever a file is uploaded with an extension that exists in AllowedFileExtensions but does not have a record in [mimetypes.php](https://github.com/vanilla/vanilla/blob/master/plugins/editor/mimetypes.php) upload fails.

We recently did a security patch [#198](https://github.com/vanilla/vanilla-patches/pull/198) that adds MIME type validation to editor uploads.

## Requested Fix

When adding a custom file extension to AllowedFileExtensions list, a record should be automatically added to mimetypes file without having to go through updating mimetypes file everytime a new custom extension is required.

**Comment by DaazKu** [comment]
We should just default to `application/octet-stream` when the extension is unknown. The file will be treated as a binary file and the browser will always try to "download" the file and not do anything else.

**Comment by LauraMakesArt** [comment]
Sprint notes

- We can implement Alex's solution above if that's deemed appropriate, so long as the end result is that a CSM can add file types to the config and they'll no longer fail to download. 

- If implementing the above solution is going to take longer than the week or needs longer consideration, we need to make an exception for some of our VIP clients and add their custom types to the list so that they can regain their expected functionality. 

The older pull request for reference: https://github.com/vanilla/vanilla/pull/7228
