### ISSUE TITLE
Translations API endpoint is slow

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7473]
Our translation API endpoint doesn't seem to be caching correctly.

![image](https://user-images.githubusercontent.com/1770056/42831998-e3872250-89bd-11e8-92a1-112fc19d32e4.png)

That is way to long for something that is supposed to be cached.

**Comment by initvector** [comment]
#7532 introduced improvements to caching with the locales API v2 endpoint. The new translations script that is included in pages is: https://vanilla.example/api/v2/locales/en/translations.js?etag=2.7

The extension handling is new since the issue was filed. It will help with caching, since some caching layers cache JavaScript files (i.e. URLs with a JavaScript extension). More important is the "etag" parameter, [which triggers custom caching headers](https://github.com/vanilla/vanilla/blob/c7b9286e5156a4366353985061e5ffc1df2ae853/applications/dashboard/controllers/api/LocalesApiController.php#L56) to indicate the content should be cached for one week. Without this, the default caching headers are served, which would typically mean no caching for signed-in users or two-minute caching for guests.

The endpoint is not performing any caching of its own. It's relying on the user's browser (or caching layers) to respect the caching headers it sends.
