### ISSUE TITLE
API v2 - Archived parameter causes Swagger issues

### ISSUE THREAD

**Issue by vladaman** [vanilla/vanilla#7538]
I can't submit call from Rest Api Swagger GUI from Vanilla Administration. Regardless of which option I check or fill in archived field the form cannot be submitted due to an error.

Using Vanilla Forum 2.6

![screenshot from 2018-07-29 08-00-27](https://user-images.githubusercontent.com/907206/43363456-8a0c89c6-9305-11e8-8efc-88cab56dc143.png)

**Comment by charrondev** [comment]
Validation is failing here because our current OpenApi 2 spec has multi-types like (boolean | null) not being joined together correctly (resulting in a type "booleannull" that does not validate).

This is currently being addressed here https://github.com/vanilla/vanilla/issues/6718#issuecomment-408922426 With PRs being worked on at the moment.

**Comment by tburry** [comment]
This should be fixed now with our switch to validating OpenAPI specs.
