### ISSUE TITLE
Rich Editor Feedback

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7576]
- [x] Focussable embeds shouldn't get a border when not focussed (move shadow inside)
- [x] Make overlay white for embeds and only show on :active state
- [x] Not Enough Margins between blocks
  - [x] Typography tweaks
- [x] Quote embed -> Remove overlay
- [x] Quote embed needs a title 
- [x] Quote embed move chevron up on title line
- [x] Quotes needs a redesign for the toggle button
- [x] Get rid of ugly yellow for spoiler
- [x] Styles for code blocks to match Dan's designs
	- [x] Looks like there's extra padding on bottom of code blocks
- [x] Increase margins between elements in editor
- [x] Set typography line height to 1.5
- [x] Spoiler icon inconsistencies
- [x] Add missing viewbox to SVGs
- [x] Opacity -> change hover
- [x] Focus -> change bg
- [x] In the case of having both hover and focus, hover styles take over

**Comment by tburry** [comment]
Here are my general list of changes:

## Changes for style.css

- [ ] Get rid of the borders, border radius on code blocks, make their backgrounds `rgba(127, 127, 127, .15)`.
- [ ] Remove the `font-size: 110%` from `.ItemDiscussion .Message`.

## Variables

I'm not sure what variables you are using so please feel free to rename stuff to what you are already using.

```scss
$font-size: 14px; // This is our font size. We don't need to set a rule for it long term, but I want to test.
$lh-condensed: 1.25; // line height for non-body text
$type-margin: $font-size;
$type-heading-margin: $type-margin * 1.5;
```

## User content changes

- [ ] All headings should have a `line-height: $lh-condensed`.
- [ ] All block-level elements should have a `margin-bottom: $type-margin`.
- [ ] All headings should have a `margin-top: $type-heading-margin`.
- [ ] All block elements with a border or background color should have a `padding: $type-margin`.
- [ ] Inline code should be `display: inline; padding: .2em .4em`.
- [ ] Lists should have a small margin between items: `li + li { margin-top: .25em }`.
- [ ] Lists should have a left margin of `1.5em` instead of 3em.
- [ ] Remove the left border and font color from embed quotes. It will use regular colors so it doesn't look weird when inline styles change color.
- [ ] Get rid of borders, border radius on spoilers. Reduce the font size on the heading to the regular font size. This probably also means the icon should be smaller to work with the smaller text.
- [ ] The spoiler hover effect can be the darker shade of text like all other buttons.
- [ ] The spoiler expander should just be the arrow button rather than the entire row. This is to remain consistent with the quote expander.
- [ ] No hover effect on any embeds. Just reduce their opacity for the active state.
- [ ] The first/last elements should have no top/bottom margins respectively.
- [ ] The first/last elements within block formats should have no top/bottom margins respectively.
- [ ] The quote header is too tall because of the expand button. This throws off the margin values. The button doesn't have to be smaller, but may need to use negative margins/absolute positioning so that the height is the same as the avatar.

Once these changes are done I want to step through variations of `$font-size` to see how the styles hold together.

## Editor changes

- [ ] The hover shouldn't be a background color. Just do the darker color like you had before. Sorry!
- [ ] I think if the above is done then the open menu color can just be the hover color rather than a transparent selected color. Let me see this change in action before a final decision.

**Comment by slafleche** [comment]
The typography issues have been moved here: https://github.com/vanilla/knowledge/issues/49
