### ISSUE TITLE
Rich Editor - Cursor not positionning correctly when moving in and out of spoiler block

### ISSUE THREAD

**Issue by patches** [vanilla/vanilla#7640]
When you move out of the spoiler block using the "up" key, the cursor is not positioning correctly if you use the "down" arrow to go back in the block. You can't type anything while the cursor is stuck at this position. 

I can only reproduce this on Firefox, it seems to be behaving properly on Google Chrome.

### When you go up:
![screen shot 2018-08-15 at 5 43 45 pm](https://user-images.githubusercontent.com/5429361/44175344-e9637680-a0b3-11e8-8eb4-295647918e28.png)

### When you try to go back:
![screen shot 2018-08-15 at 5 43 07 pm](https://user-images.githubusercontent.com/5429361/44175357-ebc5d080-a0b3-11e8-8837-5d3e46a28b0c.png)

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/6731

I'm bringing the following over from there and closing that one.

Using Shift + enter around a spoiler blot can result in broken behaviour across the editor.

**To reproduce:**

1. Make spoiler blot with text.
1. Arrow up to make a new line.
1. hold down shift and hit right arrow.

**Expected behaviour:**
The text selection will be inside of the the spoiler.

**Current behaviour:**

The selection is not visible and is currently on the spoiler's header. In fact with further messing around you can actually delete the header in this way.

__Note__: This is likely fixed with Quill 2.0's concept of a UINode.
