### ISSUE TITLE
Remove unnecessary fireEvent('BeforeTranslate')

### ISSUE THREAD

**Issue by alex-mtl** [vanilla/vanilla#7735]
Working on optimization epic I've found out this line

https://github.com/vanilla/vanilla/blob/336bdcac94498f057a1381e17286751cd6e54cda/library/core/class.locale.php#L360

That means on every t() or translate() call we do fire the event (even if there are no any listener)

I have a question: is there any good reason to fire this event that many times for each item/word/phrase we need to translate on the page.

After some additional research I've found just one potential listener plugin 'Localligator' plugin.

I suspect that this plugin is just dev tool and even if we need it time to time it should not be active in 99% of uptime on production.

My main question/suggestion for this issue:
can we just comment/remove  this fireEvent line in repo?
when anybody need to use Localligator - he can manually uncomment this line and collect info, but not ever push uncommented line back to repository?

**Comment by linc** [comment]
Yes, let's get that event turned off by default.

I suggest only firing the event when in debug mode (there's a config for that), or modify Localigator to enable a generic-named config setting (`Garden.Locales.CollectEvents` or something) and then the event only fires if that config setting is true.

I don't like a "uncomment code to make a tool work" scenario very much because it's secret knowledge that's hard to communicate. That said, if the config solution I describe is too expensive, I'd be OK with it in this 1 instance as long as you update the Localigator README to clearly explain that, and document the line in core so we don't accidentally delete it later.

**Comment by DaazKu** [comment]
No matter the decision, never forget that anyone could have used an event that we remove.
We have no control over what is used and what is not. Scanning our own plugins is not enough. Good example: https://open.vanillaforums.com/addons

Deprecating the event and putting that in our releases note should be the first step.
If we decide to be more agressive about it the config route is a good idea.

**Comment by linc** [comment]
> No matter the decision, never forget that anyone could have used an event that we remove.

In the broad case, I agree. They should get deprecated before removal.

In this specific case, I think it's safe to be more aggressive. We added it for a very narrow use case, I've never heard of it being used elsewhere, it hasn't been around very long, and the benefit to removal is very big.

Also, wrapping it with a config-based conditional would let folks sidestep that concern fairly easily.

**Comment by R-J** [comment]
I have more than 100 (even ancient) plugins installed and uncountable snippets where I've tested even absurd things. The only place where I can find that event being used is in an old version of vanillas own Addons application. In the current version of the Addons applications class.hooks.php this method is no longer included.

**Comment by alex-mtl** [comment]
@linc please check implementation:

https://github.com/vanilla/vanilla/pull/7737/files
