### ISSUE TITLE
Roles: Deleting roles and updating UserRole table

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7758]
### Issue

When deleting a role and selecting a replacement role, the role is removed from GDN_Role but not GDN_UserRole.
[class.rolemodel.php#L750](https://github.com/vanilla/vanilla/blob/fix/delete-orphaned-roles/applications/dashboard/models/class.rolemodel.php#L750) is not evaluated in that case.

### API Call

This was noticed during an api call to users [api/v2/users ](https://docs.vanillaforums.com/help/apiv2/swagger/#/Users/get_users).
![screen shot 2018-09-11 at 3 08 09 pm](https://user-images.githubusercontent.com/31856281/45381921-b4741200-b5d4-11e8-89f7-3c4cb42f6339.png)

### To Replicate
![screen shot 2018-09-11 at 3 06 14 pm](https://user-images.githubusercontent.com/31856281/45381766-462f4f80-b5d4-11e8-8ecf-b6e23e072ca3.png)

**Comment by topcheese13** [comment]
So here's what I think the issue should be here, this is an example for this case but I think it's a good reference for any other issue in the future. I know we aren't always as deep in the process when creating an issue, this is kind of a best case scenario but I think this should be the goal for every issue we investigate.

The problem
---
We have multiple customers reporting API errors on the `api/v2/users` endpoint. The error is a validation error, saying the role name is required. We have identified the cause of the error being orphaned user roles records with a RoleID that doesn't exist (anymore).

The cause
---
When deleting a role you can select a replacement role for the soon to be deleted role.

For example, I could want to delete role "DeleteMe" with ID 30 and replace it with role "KeepMe" with ID 40. We do this by calling the `role/delete/{id}` endpoint of the `RoleController`. From there we call the `deleteAndReplace` method of the `RoleModel`.

```
public function deleteAndReplace($roleID, $newRoleID) {
        // First update users that will be orphaned
        if (is_numeric($newRoleID) && $newRoleID > 0) {
            $this->SQL
                ->options('Ignore', true)
                ->update('UserRole')
                ->join('UserRole urs', 'UserRole.UserID = urs.UserID')
                ->groupBy('urs.UserID')
                ->having('count(urs.RoleID) =', '1', false, false)
                ->set('UserRole.RoleID', $newRoleID)
                ->where(['UserRole.RoleID' => $roleID])
                ->put();
        } else {
            $this->SQL->delete('UserRole', ['RoleID' => $roleID]);
        }

        // Remove permissions for this role.
        $permissionModel = Gdn::permissionModel();
        $permissionModel->delete($roleID);

        // Remove the role
        $result = $this->SQL->delete('Role', ['RoleID' => $roleID]);
        return $result;
    }
```

The update query that happens first when you have a replacement role results in this
```
update ignore `GDN_UserRole` `UserRole`
join `GDN_UserRole` `urs` on UserRole.UserID = urs.UserID
set `UserRole`.`RoleID` = :UserRoleRoleID
where `UserRole`.`RoleID` = :UserRoleRoleID0
```

The ignore prevents errors like `Duplicate entry '65-35' for key 'PRIMARY'` from happening but it also leaves us open to have orphaned records in the `UserRole` table. This problem seems to have been there for a while, it's only the API endpoint validation that really ends up being an actual problem, but, this was always a problem, we shouldn't have orphaned records simply sitting there.

The proposed fix
---
I would simply remove the else statement of the if/else update query and always run the delete user role query AFTER the update query has ran successfully. This way we will update the records we need to without triggering errors because of the ignore options that is used but we will also delete the orphaned records created by this logic. Otherwise, we need to delete the user roles records associated with the to be deleted role of the users having both the to be deleted and replacement role. Although the logic would be slightly better I think we will need more operations and more queries to accomplish this so I would like the 1st option better.

Same function with the proposed fix:
```
public function deleteAndReplace($roleID, $newRoleID) {
        // First update users that will be orphaned
        if (is_numeric($newRoleID) && $newRoleID > 0) {
            $this->SQL
                ->options('Ignore', true)
                ->update('UserRole')
                ->join('UserRole urs', 'UserRole.UserID = urs.UserID')
                ->groupBy('urs.UserID')
                ->having('count(urs.RoleID) =', '1', false, false)
                ->set('UserRole.RoleID', $newRoleID)
                ->where(['UserRole.RoleID' => $roleID])
                ->put();
        } 

        // Remove permissions for this role.
        $permissionModel = Gdn::permissionModel();
        $permissionModel->delete($roleID);

        // Remove user roles associated to the role we are about to delete
       // Also removes user roles records of users that were ignored in the update query 
        $this->SQL->delete('UserRole', ['RoleID' => $roleID]);
        // Remove the role
        $result = $this->SQL->delete('Role', ['RoleID' => $roleID]);
        return $result;
    }
```
