### ISSUE TITLE
Rich posts not rendering correctly when reporting a post

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#7764]
When using the Rich Editor and the reporting addon the following error appears. It says "There was an error rendering this Rich Post". The content of the post is just regular text, no rich embeds in this instance.

![screen shot 2018-09-12 at 11 33 06 am](https://user-images.githubusercontent.com/24961134/45436129-0a51c400-b680-11e8-98bb-c511aaecdbeb.png)

**Comment by charrondev** [comment]
Confirmed. The issue seems to be some conflict with the `Reporting2` plugin.

**Comment by charrondev** [comment]
Additional reproduction by @Krisstoffer

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a spammer
2. ~~beat them stupid(er)~~ Politely Flag the issue
3. Get all excited because the bug exists on the developers' site so it proves you are not crazy! 

**Expected behaviour**
Shows post with no errors.

**Screenshots**
![Screen Shot 2019-05-30 at 15 22 23](https://user-images.githubusercontent.com/700503/58616080-5a94b300-82ef-11e9-9f14-f57c30380d99.png)
