### ISSUE TITLE
Reliance on PDO returning INT column as PHP int

### ISSUE THREAD

**Issue by rgphilpott** [vanilla/vanilla#7770]
I believe that **mysqlnd** is the only PDO MySql driver that can be relied upon to return an INT column as a PHP int - other drivers may return a PHP string. mysqlnd is not listed as a requirement, but there is code that relies on its behaviour.

If the CategoryID passed to `categoryModel->get()` is a string, it is assumed that it is a slug rather than a primary key, and so the category lookup fails. This is an issue when incrementing discussion counts and 'most recent discussion' links in a category when a new discussion is added, as the CategoryID obtained from the DIscussion record is passed as a string. See also https://open.vanillaforums.com/discussion/35885/post-count-not-updating
 
In this case, either the CategoryID needs to be cast to an int when it's retrieved from the DB (eg, in `CategoryModel->incrementLastDiscussion()` and `CategoryModel->updateLastPost()`), or `categoryModel->get()`  needs changing to use `is_numeric` rather than `is_int`. The latter would break any forum that has all-numeric category slugs -- I don't know if that a possibility?

**Comment by R-J** [comment]
The question why post counts are not changing comes up periodically on the open source forum.

I think "is_int" should be avoided if possible, since this leads to trouble in such constellations. Converting/ensuring the type is annoying but I don't see a better approach. In the case of post counts not increasing, the code in DiscussionModel->save() looks like that:
~~~
                // Get CategoryID of this discussion
                $discussion = $this->getID($discussionID, DATASET_TYPE_OBJECT);

                // Update discussion counter for affected categories.
                if ($insert || $storedCategoryID) {
                    CategoryModel::instance()->incrementLastDiscussion($discussion);
                }
~~~

One small (super ugly) line would prevent further problems in this case:
`$discussion->CategoryID = intval($discussion->CategoryID);`

But my personal impression is that mysqlnd should be a requirement. That's more of a database issue than an application issue. Maybe a warning can be added to the dashboard?

**Comment by charrondev** [comment]
@R-J I definitely agree on having a warning. I think we should be showing prompts for this and missing extensions as well if possible.

I don't know if we have an existing design for any warnings like that in the dashboard, but we have discussed having a goto section in the dashboard to surface potentially conflicts and some icons to indicate that there is a problem. Plans for that are still a ways on our roadmap though.

## Actions right now

Right now we can do a couple things:

- We currently check for extensions on installation. We can add this check to there.
- We could run those same checks during utility update, except instead of throwing any errors, just log warnings.
