### ISSUE TITLE
Problems getting API calls to work

### ISSUE THREAD

**Issue by eddieray** [vanilla/vanilla#7842]
I've set up a brand new instance of Vanilla 2.6.1 from scratch.

I have a user account using the admin role, and I've added the privileges needed to the admin role that aren't enabled by default.  I created an API key in the user account.

I'm trying to verify that I can query things at this point and it is hit or miss:

`
curl -G -H - https://server/vanilla/api/v2/discussions < tokenfile

... works fine

curl -G -H - https://server/vanilla/api/v2/categories < tokenfile

... gives the error:

{
    "message": "You need the Garden.SignIn.Allow permission to do that.",
    "status": 403,
    "permissions": [
        "Garden.SignIn.Allow"
    ],
    "description": null
}
`
Most things give some kind of error about permissions or "not found":

`
$ ./test.sh users
{
    "message": "You need one of Garden.Users.Add, Garden.Users.Edit, Garden.Users.Delete permissions to do that.",
    "status": 403,
    "permissions": [
        "Garden.Users.Add",
        "Garden.Users.Edit",
        "Garden.Users.Delete"
    ],
    "description": null
}
$ ./test.sh addons
{
    "message": "You need the Garden.Settings.Manage permission to do that.",
    "status": 403,
    "permissions": [
        "Garden.Settings.Manage"
    ],
    "description": null
}
$ ./test.sh badges
{
    "message": "/api/v2/badges not found.",
    "status": 404,
    "description": null
}
`
Querying the "discussions" URL actually works!  Querying the comments for one of the discussions works.  That's about it.

It seems like something very basic is wrong here.

**Comment by charrondev** [comment]
Unless you can narrow this down to a specific reproducible issue, with steps that another user could use to reproduce the issue locally, I'm afraid there's not much we can do here.

I'd be inclined to believe this is either some role being misconfigured, or something that was fixed in a later release. If you'd like assistance debugging your roles/permissions configuration, I'd recommend trying over at the our [OSS User Forums](https://open.vanillaforums.com/).

If you do manage to reproduce this issue consistently and determine this is definitely a bug feel free to re-open the issue with the steps. If you find that some piece of documentation was missing in how to configure your user/token/roles you can file an issue or open a pull request on our [documentation repository](https://github.com/vanilla/docs)
