### ISSUE TITLE
Make swagger doc generation explicit instead of implicit

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7939]
Currently the generation of swagger documentation happens as a side affect of creating your input/output schema. Events are fired when calling the `Vanilla\Web\Controller::schema()` method, which generate the doc.

## The issue

Schema can be polluted quite easily if the distinct actions of defining input/output schema's are not handled in the proper order immediately after each other. @alex-mtl could comment more on the issue.

## Recommendations

A cleaner structure for handling schemas could look like the following:

- Deprecate `Vanilla\Web\Controller::schema()`.
- Create an `ApiEndpointSchema` object that represents the schema for an endpoint. It should know be made up of
  - an input \Garden\Schema,
  - multiple output \Garden\Schema (for different response codes)
  - an endpoint name 
  - an http verb (patch, get, post ,etc)
  - a `validate($input)` method.
  - a `filterValidate($output)` method.
- Expose through some class or method a manner to explicitly register the schema of an API endpoint with a signature similar to the following: `registerApiSchema(ApiEndpointSchema $apiSchema)`.
- For each endpoint requiring documentation create a class extending `ApiEndpointSchema` for validation. Inheritance and traits can be used to share logic and common schemas. Each endpoint method should:
  - Create one of these objects.
  - Register it.
  - Use it to validate its inputs/outputs.

**Comment by initvector** [comment]
How about starting with a valid OpenAPI spec and having the ability to extract and transform relevant portions into instances of `garden-schema` or your proposed `ApiEndpointSchema` class?

For example:
1. Create a OpenAPI spec for my endpoint. This could be in JSON, an associative array or whatever. Make sure it's valid.
1. Create the endpoint controller. Part of this controller's initialization will be responsible for loading the OpenAPI spec from wherever.
1. Controller methods generate a "schema" instance from the loaded spec, based on a requirements (e.g. `$this->generateSchema($path, $verb, $type)` where `$type` is "parameters" or "responses"). I'd like to keep input/output schemas separate in the individual controller methods, instead of one giant endpoint-wide "schema" that's used for input and output validation across everything, but I'm not married to the idea.
1. Use the schema, generated from the OpenAPI spec, to validate input and output.
1. Generating documentation is a matter of loading/merging the original OpenAPI spec(s) into whatever documentation generator is used.

We've internally discussed a similar approach in the past. The primary difference is we'd be designing APIs in the spec and generating our validation schemas from that. This is in contrast to the current workflow, where the spec is generated from the schemas. It's a matter of perspective: do we want to document how it *should* work, per design, and at least be able to enforce that on input and output validation? It should also help with ensuring we start off with valid endpoint designs, so long as we're vetting the OpenAPI spec before building.

Also note: add-ons are still going to need to hook in to modify these schemas, be it to update enum values, registering a field on a response or whatever else.

**Comment by charrondev** [comment]
In my mind it is much easier to work with programming constructs in the PHP rather than JSON, not to mention much more flexible. Have you ever tried to actually write an open API spec as JSON? It's tedious.

I'd rather see us be more explicit about how we define our schema's in code, and have an automated test running in CI that ensures we are generating a valid spec. This seems like it would require a lot less tooling on our end, the big one being IDE tooling. As far as I've seen there does not exist a tool to work on an openAPI spec in multiple files with IDE support.

**Comment by charrondev** [comment]
> The latter seems more prone to errors, as we've seen. Having CI validate whatever specs we have is a very good idea, but it's only going to ensure it's valid per the OpenAPI format. If we're generating specs from schemas, it's possible to misrepresent types or juggle a reference and still have it be in a valid OpenAPI format.

I view the large issue has been us not dedicating time to fixing the issues and not settling on the spec to target. It's probably something that could have been settled and fixed in less than 1 sprint if we had had the manpower or will to do it when we first started noticing issues.

The counterpoint here is that its possible if we're going from OpenAPI to validation that we will mess up the generated validator, which in my mind is worse. I'd rather have a mistake in documentation than a mistake in the product.

**Comment by initvector** [comment]
> The counterpoint here is that its possible if we're going from OpenAPI to validation that we will mess up the generated validator, which in my mind is worse.

That is a valid point! But I think that's much easier to create tests for.

**Comment by charrondev** [comment]
Completed. See the `/api/v2/openapi/v3`
