### ISSUE TITLE
APIv2: Token based authentication doesn't apply permissions granted through ranks

### ISSUE THREAD

**Issue by JReko** [vanilla/vanilla#7950]
When you setup a rank you have the option to attribute the permission of a role through the Rank.

>Users with this rank will gain the permissions of this role.

My setup
---
I have 1 Test user.
He has and only has a standard Member role.
He has a Test rank (manually applicable) that grants the permission of the Administration role.

The problem 
---
If I browse to the API endpoint on the site, i.e. https://dev.vanilla.localhost/api/v2/users.
* It works as expected and returns the expected json.

If I make a curl request using this user's access token I receive this permission error.
```
{
    "message": "You need one of Garden.Users.Add, Garden.Users.Edit, Garden.Users.Delete permissions to do that.",
    "status": 403,
    "permissions": [
        "Garden.Users.Add",
        "Garden.Users.Edit",
        "Garden.Users.Delete"
    ],
    "description": null
* Connection #0 to host dev.vanilla.localhost left intact
}
```

The cause
---
To put it very simply the problem comes from the moment the session is created.

When browsing the site the session is created through:
```
class.session.php:442, Gdn_Session->start()
class.auth.php:59, Gdn_Auth->startAuthenticator()
bootstrap.php:396, require_once()
index.php:22, {main}()
```

When making an API call and using the access token to authenticate yourself, the request goes through the same stack above but since we have no UserID the session is started and we load the permissions of a guest.
```
public function start($userID = false, $setIdentity = true, $persist = false) {
        if (!c('Garden.Installed', false)) {
            return;
        }

        $this->permissions = new Permissions();

        // Retrieve the authenticated UserID from the Authenticator module.
        $userModel = Gdn::authenticator()->getUserModel();
        $this->UserID = $userID !== false ? $userID : Gdn::authenticator()->getIdentity();
        $this->User = false;
        $this->loadTransientKey();

        // Now retrieve user information.
        if ($this->UserID > 0) {
```
```
// Load guest permissions if necessary
        if ($this->UserID == 0) {
            $guestPermissions = $userModel->getPermissions(0);
            $this->permissions->setPermissions($guestPermissions->getPermissions());
        }
```

To assign the permissions through a token based authentication we use a hook

https://github.com/vanilla/vanilla/blob/f841b0f4dbedad56160694884324640acf994afe/applications/dashboard/settings/class.hooks.php#L624
https://github.com/vanilla/vanilla/blob/f841b0f4dbedad56160694884324640acf994afe/applications/dashboard/settings/class.hooks.php#L666

Which in theory should work but since the ranks plugin is hooking before the dashboard on this event `gdn_dispatcher_appStartup_handler` with this call

```
public function gdn_dispatcher_appStartup_handler($sender) {
        if (!Gdn::session()->UserID) {
            return;
        }
        RankModel::applyAbilities();
    }
```

"Abilities" are never applied.

The fix
---
To try and make this work I changed this https://github.com/vanilla/vanilla/blob/f841b0f4dbedad56160694884324640acf994afe/applications/dashboard/addon.json#L7 to be `Priority: 1000000`, simply to make sure it was hooking before ranks (clear your cache folder). The API was then working as expected for a curl request with an access token and admin permissions issued through a rank.

I'm not sure how reckless it would be to play around with the priority of the dashboard addon but this is a potential way to fix this.

**Comment by topcheese13** [comment]
We would like to know what @initvector thinks on this. We all agree that simply changing the priority of the dashboard addon might be dangerous. Basically we want to know how complex and dangerous the will be before deciding if we want to tackle it right now or not.

**Comment by initvector** [comment]
Since we first discovered this, I've also noticed other issues regarding the late stage that token authentication is happening. Vanilla has some HTTP middleware that depends on a user's permissions. Since those permissions aren't loaded at the time of dispatching with token-based authentication, the checks are never going to be accurate.

Vanilla's normal authentication starts near the end of it's bootstrap, before dispatching.
https://github.com/vanilla/vanilla/blob/6ad8ebc2421f259871ae99a5b4edc73eae4217a0/bootstrap.php#L395-L396

As you've pointed out, the token-based authentication is started by the "AppStartup" event, which is triggered by the dispatcher's `start` method...

https://github.com/vanilla/vanilla/blob/6ad8ebc2421f259871ae99a5b4edc73eae4217a0/library/core/class.dispatcher.php#L192-L194

...which is called at the end of Vanilla's index file.

https://github.com/vanilla/vanilla/blob/6ad8ebc2421f259871ae99a5b4edc73eae4217a0/index.php#L27-L29

When it comes to tokens, Vanilla is only authenticating after the dispatcher has been instantiated. This means DIC rules executed as part of that instantiation aren't going to have a relevant user session.

Here's an example:

https://github.com/vanilla/vanilla/blob/6ad8ebc2421f259871ae99a5b4edc73eae4217a0/bootstrap.php#L166-L170

In this case, Vanilla configuring a piece of middleware the dispatcher will use. Part of that configuration relies on reading the user's permissions. Those permissions will always be the default when using token-based authentication, because the session won't have current values until after the dispatcher has been instantiated and the `start` method is called.

Vanilla's authenticators (cookie and token) running at two separate times during the page load, in two separate areas, is the real root cause of these issues. If we could move authentication into a single unified point (i.e. authenticate at the same time, regardless of type), it would probably resolve things.
