### ISSUE TITLE
Research GraphQL implementation

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8143]
Vanilla has a RESTful API. It has its limitations. [GraphQL](https://graphql.org) may be the answer to many of those issues. Research should be done on a potential implementation of adding a GraphQL layer to Vanilla's API.

1. Document issues and limitations with the RESTful API that could be fixed by a GraphQL implementation, in addition to general improvements that could be achieved.
1. Research libraries to help assist with implementing GraphQL for Vanilla's API.
1. Cite how GraphQL could be used for the issues specifically cited in step one.
1. File issues for next steps.

**Comment by charrondev** [comment]
**REST API limitations / issues**

I have not looked into implementation of a GraphQL server. I've only looked into the client implementation at the moment.

- In a REST API caching pieces of data between requests (that are not the same exact request) must be implemented in a bespoke manner if done at all. Certain GraphQL implementations can implement incredibly efficient client side caching automatically, without having to think about it. This could replace a lot, if not almost all of our redux code.
- There is no need to implement separate expand fields/fragment endpoints in a client implementation. REST clients are doomed to either overfetch/underfetch data. A graphQL implementation can fetch exactly the requested fields.
- REST APIs usually require multiple server requests to fetch all the data needed for a particular page. Sometimes these depend on each other which can cause really bad UX on the client for users with higher latency. GraphQL serves similarly to how how a multi-endpoint would, except using a well defined, schema based, standard technology, rather than a bespoke multi-endpoint implementation would.

**Some reading resources**

- [GraphQL: A success story for PayPal Checkout](https://medium.com/paypal-engineering/graphql-a-success-story-for-paypal-checkout-3482f724fb53)
- [Netflix - Our learnings from adopting GraphQL](https://medium.com/netflix-techblog/our-learnings-from-adopting-graphql-f099de39ae5f)
- [From REST to GraphQL](https://0x2a.sh/from-rest-to-graphql-b4e95e94c26b)
- [Wrapping a REST API in GraphQL](https://graphql.org/blog/rest-api-graphql-wrapper/)
- [Reducing our Redux code with Apollo](https://blog.apollographql.com/reducing-our-redux-code-with-react-apollo-5091b9de9c2a)
- [Wrapping a REST API in GraphQL](https://graphql.org/blog/rest-api-graphql-wrapper/)

**Research libraries to help assist with implementing GraphQL for Vanilla's API**

- [Apollo](https://github.com/apollographql) - Community Based, Node Server + Clients for Typescript, Swift, Java, ~10k github stars
- [Relay](https://github.com/facebook/relay) - Facebook, Node Server + Javascript client, 11k github stars

There is no large first party PHP graphql implementation, but it seems there is a very well defined spec for how these things are supposed to work. https://facebook.github.io/graphql/June2018/
