### ISSUE TITLE
Set Keystone as default theme and Rich Editor as default on

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8146]
Improve our defaults before the 2.8 release.

**Comment by charrondev** [comment]
I figured I'd triage a few advanced editor bugs that were likely a wont-fix before (due to the abandoned nature of our previous formatter WYSIHTM5).

If you could just clarify @linc my understanding is that advanced editor would only get security patches if necessary after making rich editor the default.

- https://github.com/vanilla/vanilla/issues/6076
- https://github.com/vanilla/vanilla/issues/6114
- https://github.com/vanilla/vanilla/issues/5626
- https://github.com/vanilla/vanilla/issues/5151
- https://github.com/vanilla/vanilla/issues/3433
- https://github.com/vanilla/vanilla/issues/6697
- https://github.com/vanilla/vanilla/issues/3352
- https://github.com/vanilla/vanilla/issues/5291
- https://github.com/vanilla/vanilla/issues/5571
- https://github.com/vanilla/vanilla/issues/5663
- https://github.com/vanilla/vanilla/issues/5860
- https://github.com/vanilla/vanilla/issues/6829
- https://github.com/vanilla/vanilla/issues/4243
- https://github.com/vanilla/vanilla/issues/4480
- https://github.com/vanilla/vanilla/issues/5612
- https://github.com/vanilla/vanilla/issues/6979
- https://github.com/vanilla/vanilla/issues/2978
- https://github.com/vanilla/vanilla/issues/3564
- https://github.com/vanilla/vanilla/issues/4296
- https://github.com/vanilla/vanilla/issues/5208
- https://github.com/vanilla/vanilla/issues/5399
- https://github.com/vanilla/vanilla/issues/5499
- https://github.com/vanilla/vanilla/issues/5806
- https://github.com/vanilla/vanilla/issues/5861
- https://github.com/vanilla/vanilla/issues/5907

And a few that could either be easily closed (with a minimum effort) or should be closed and re-opened to target rich editor.

- https://github.com/vanilla/vanilla/issues/3156
- https://github.com/vanilla/vanilla/issues/4295
- https://github.com/vanilla/vanilla/issues/5386

**Comment by charrondev** [comment]
There are also a few that could probably be closed with keystone.

- https://github.com/vanilla/vanilla/issues/3355

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8302
