### ISSUE TITLE
Be able to delete the profile photo of others

### ISSUE THREAD

**Issue by hex0wn** [vanilla/vanilla#8246]
**Describe the bug**
I found a bug that I can delete the profile photo of other user. I'm not sure that I should submit a report in hackerone or post a public issue here.

**Comment by charrondev** [comment]
Please submit a report on HackerOne. https://hackerone.com/vanilla

If submitted there and the issue is verified, and is not in our excluded criteria, then you may be eligible for a bounty.

Alternatively security sensitive issues may be reported by emailing support@vanillaforums.com with a full description of the issue.
