### ISSUE TITLE
Rich Text Editor: Pasting text into code block removes spaces

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8315]
I pasted a raw text document (created in TextEdit) into an empty code block. This was the result:

<img width="770" alt="screen shot 2019-02-06 at 11 03 32 am" src="https://user-images.githubusercontent.com/117672/52358047-486fcb80-2a05-11e9-9f72-07cbf483d950.png">

**Comment by charrondev** [comment]
I cannot reproduce as of 3.0

![image](https://user-images.githubusercontent.com/1770056/60837748-f17a4800-a196-11e9-9556-35e8ca06d0b8.png)

**Comment by R-J** [comment]
I've experienced the same problem on open.vanillaforums.com 2 days ago. I'll try to find recreatable steps

**Comment by R-J** [comment]
1. Copy the code from [this comment](https://open.vanillaforums.com/discussion/comment/257479/#Comment_257479)
2. Paste it to a simple text editor so that the formatting is gone
3. Copy that plain text and paste it to the comment box
4. Format it as code
5. Mark all the code in the code block
6. Paste again and the pasted text has no spaces between the words any more

**Comment by charrondev** [comment]
After some additional testing this seems to be cross-browser issue.

- Chrome - Works as expected.
- Firefox - Strips spaces but leaves tabs.
- Safari - Strips tabs but leaves spaces.

**Comment by charrondev** [comment]
I've done some testing as of Vanilla 3.3 (2019.017) and this is no longer an issue.
