### ISSUE TITLE
Keystone theme will give a fatal error if turned on when Advanced Search is not enabled

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#8324]
When you activate the Keystone theme, if you don't have the Advanced Search Plugin turned on, you get a fatal error.

**To Reproduce**
1. Turn off Advanced Search if it is turned on.
2. Choose the Keystone theme from themes.
3. Visit the home page of your forum.
4. Get a fatal error.

**Comment by charrondev** [comment]
This is because the default.master.tpl for keystone uses the `{searchbox_advanced}` which only comes from the advanced search addon. This crashes because the function doesn't exist in the compiled template, even though it's in a conditional.

It should be `{module name="AdvancedSearchModule"}` instead.
