### ISSUE TITLE
Hero Image might have a wrong license

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8341]
At least that's what I guess. It shows "proprietary" where I would expect "GPL-2.0-only"

**Comment by charrondev** [comment]
Good catch. We moved it form our proprietary repo and forgot to move change that licence. I'm thinking we should remove the field for the same rationale that I've outlined here: https://github.com/vanilla/vanilla/issues/8342.

We don't intend to publish this addon separately from Vanilla.

_Side Note:_ We're planning on probably just rolling this directly into core instead of being an addon at all.
