### ISSUE TITLE
Keystone: Reaction avatar coloring and placement

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8357]
When configured so, reactions show a list of avatars with reactions  icons over them. The reaction icons are currently white and don't show up properly. This has to do with the fact the design was done when we had square avatars. We are going to need a design tweak and fix in the CSS.

<img width="194" alt="national_suicide_prevention_lifeline_guide_released__dealing_with_suicide_ _vanilla_staff" src="https://user-images.githubusercontent.com/97432/52521434-26648c00-2c45-11e9-98d1-31b1db74e1d1.png">

I recommend trying to put the icons inside a transparent black circle of their own or something like that.

**Comment by igraziatto** [comment]
This issue is related to this: https://github.com/vanilla/vanilla/issues/8296

**Comment by igraziatto** [comment]
Since this section never had some thought put into it I did a few possible variations:

![screen shot 2019-02-11 at 4 12 55 pm](https://user-images.githubusercontent.com/31521020/52594865-89f3e280-2e1a-11e9-9287-d1fbc8c377bd.png)
![screen shot 2019-02-11 at 4 13 02 pm](https://user-images.githubusercontent.com/31521020/52594866-89f3e280-2e1a-11e9-8266-73f503925e85.png)

For these ones I incresed the avatar size from 24px to 30px and the reaction icon to 17 pixels:
![screen shot 2019-02-11 at 4 13 59 pm](https://user-images.githubusercontent.com/31521020/52594867-89f3e280-2e1a-11e9-9bfb-36b4dc8d1f64.png)
![screen shot 2019-02-11 at 4 15 53 pm](https://user-images.githubusercontent.com/31521020/52594868-89f3e280-2e1a-11e9-9717-4ece6522733c.png)
![screen shot 2019-02-11 at 4 16 14 pm](https://user-images.githubusercontent.com/31521020/52594869-8a8c7900-2e1a-11e9-8289-0b8efe25dbd1.png)

**Comment by ElisaAlmeida** [comment]
I did an option with the avatar size still 24px and the reaction icon 12px. (the reaction icon is still aligned to the left but 2px more to the left and 2px down). So the size of the avatar icon + reaction icon together is 26px. Transparent 50%. 

<img width="200" alt="screen shot 2019-02-18 at 9 46 04 am" src="https://user-images.githubusercontent.com/45467951/52958546-48a38b80-3362-11e9-94be-0bb594788f4f.png">

Let me know what you think.

**Comment by tburry** [comment]
The issue here is the icons are done with a font so we cannot do that white
outline like that. We can do a circle for every reaction but in that case
there should be a bit more padding. You would need enough in the case the
icon is a square.

**Comment by ElisaAlmeida** [comment]
I did with more padding. The size of the circle is 14px.

<img width="481" alt="screen shot 2019-02-19 at 11 11 20 am" src="https://user-images.githubusercontent.com/45467951/53030156-4f043700-3438-11e9-873a-fc490d529fdc.png">

I did a mockup with the current icons and the suggestion:

<img width="595" alt="screen shot 2019-02-19 at 11 19 00 am" src="https://user-images.githubusercontent.com/45467951/53030234-6cd19c00-3438-11e9-9496-687bfcbdfe5c.png">

**Comment by tburry** [comment]
Okay let’s go with this and assign the issue to Isis.
