### ISSUE TITLE
Smart Embeds not working

### ISSUE THREAD

**Issue by erichnsy** [vanilla/vanilla#8453]
Version 2.8, Rich Editor

Smart embeds not always working. Example: 

https://uscale.org/discussion/19/model-for-community-development-amigos-de-santa-cruz-of-guatemala

link
https://www.youtube.com/watch?v=GiWK4nzyaZw

is not embedding. Any idea why not?

![image](https://user-images.githubusercontent.com/47966056/53318807-4e7afe80-3885-11e9-9eb9-8d4d21dc1c8f.png)

**Comment by charrondev** [comment]
You have to hit enter at the end of the line or use the embed dialogue box at the bottom of the editor. This was done intentionally in order to give users more control over their content and to try and make the input match the output as much as possible. It allowed to remove the "preview" button for instance which we found to a positive UX decision.

**Comment by erichnsy** [comment]
Thanks & sorry I missed that--the documentation didn't mention that tiny extra fact.

https://docs.vanillaforums.com/help/posting/smart-embed/

would best be qualified

"Vanilla automatically embeds content from many social media sites. When creating a post, simply paste the URL into the editor [(and then hit enter at the end of the line)], like so:"

**Comment by charrondev** [comment]
I'm going to update that but the difference is actually going to be to rename the whole category to "Advanced Editor". It only applies to our previous editor, not the new one.

This is the doc you should be looking for: https://docs.vanillaforums.com/help/addons/rich-editor/

**Comment by erichnsy** [comment]
Oh I see. Thanks again.
