### ISSUE TITLE
MediaItemModule->tag is not accessible

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8674]
The MediaItemModule has a private property ("$tag The root-level tag of the media item") which can be set when a new MediaItemModule is created but since it is a private property, it cannot be accessed afterwards and therefore is useless.

The module needs at least a getter method for that property so that it can be used in views.

**Comment by charrondev** [comment]
What are you trying to achieve with this? What's the use case for accessing this tag again afterwards?

**Comment by R-J** [comment]
The property is defined like that:
~~~
    /** @var string The top-level HTML element for the Media Item. */
    private $tag = 'div';

    /** @var array The top-level attributes for the Media Item. */
    private $attributes = [];
~~~

The question is not why I want to change it; by now I cannot use it. Defining a versatile view for that module would start like that (simply using `$this->tag` throws an error):

~~~
<?php /** @var MediaItemModule $this */ ?>
<<?php echo $this->getTag(); ?> <?php echo attribute($this->getAttributes()); ?>>
    <?php if ($this->getImageHtml()) { ?>
~~~

Only that gives the html that the module describes. The three current views have a hardcoded div at their beginning which is "wrong".

I agree that it might not needed to implement a setter method, but imagine that this module is passed into an event so that a plugin developer can change it before it gets rendered. In that case all the crucial properties should be not only readable but also writeable.
Although that case is very theoretical, I'd ask you why **not** give it a setter if it needs to have a getter anyway? :wink:

**Comment by charrondev** [comment]
Makes sense I guess. I will say I hadn't thought about it very much because we haven't made much new using `Gdn_Module` or `Gdn_Asset` in years & likely never will again.

Looking a little bit deeper I don't see anything actually utilizing that tag though and we have no intention of defining a "versetile" view for it in this current system. I'd rather just delete the unused private property than add a getter/setter or it.

**Comment by R-J** [comment]
I assume "I'd rather" means "please open a new PR"? 😁 
Will do, but maybe not today. But it's only cosmetic anyway.

By the way: I found the idea to use a module in such a way a great idea compared to the old helper_function.php writeSomething() approach and adopted it. But I do it now by simply passing an item to a "blank" module instead of trying to reuse the MediaItemModule, which was my first approach. 

After describing that and hearing that you see this as a dead end I will reconsider using simple child views, though... 💡  😖

**Comment by charrondev** [comment]
There's nothing wrong with creating your own `Gdn_Module` by the way and it be in the framework indefinitely. I just don't think we'll be updating any of our own sub classes other than to convert them away to our new system.

Out custom services team writes them occasionally, but I don't particularly like `Gdn_Module` because it doesn't work well with dependency injection, doesn't have any method of composition, and every existing instance we have uses potentially insecure views (not written in a templating engine that escapes XSS by default).
