### ISSUE TITLE
Search Results: There was an error rendering this rich post.

### ISSUE THREAD

**Issue by rami7250** [vanilla/vanilla#8680]
I have the Vanilla Version 2.8.1 and when i try to search some text in search i got the results but with an error underneath:
There was an error rendering this rich post.

See attched
![search](https://user-images.githubusercontent.com/1419822/55944055-71ece380-5c50-11e9-9020-979ed5b9cf6c.jpg)

**Comment by charrondev** [comment]
Please use our issue template when created a new issue. For us to be able to make any progress on an issue like this is must have reproduction steps.

**Comment by R-J** [comment]
In version 2.8.1 and also in master branch, search results with format Rich are not rendered correctly, only the above message applies. On open.vanillaforums.com this is not the case, which is because that forum uses AdvancedSearch.

I assume the problem is the searchExcerpt function
$row['Summary'] = searchExcerpt(htmlspecialchars(Gdn_Format::plainText($row['Summary'], $row['Format'])), $searchTerms);

It takes 200 characters from the raw text from the db which doesn't play well with the rich format.

**Comment by alex-mtl** [comment]
Not sure if that is the case but I think I had that message as well when did some tests with **empty** body. @rami7250 do you have any content in that Test discussion?

**Comment by Krisstoffer** [comment]
I have encountered this issue on a clean install of 3.0 RC - using the rich editor from the start, no search plugins - all search results show below the title "There was an error rendering this rich post."

**Comment by charrondev** [comment]
It looks we've entirely overlooked the simple search, likely because we use advanced search on every infrastructure site.

This is likely a case of search excerpts not calling `Gdn_Format::excerpt()` properly (or calling some other method instead).

**Comment by charrondev** [comment]
I've gone in and made a PR in it. I'm making a release tomorrow, so I'm trying to get it in before that.
