### ISSUE TITLE
Notification are translated to other users language

### ISSUE THREAD

**Issue by Kaspar-K** [vanilla/vanilla#8785]
**Describe the bug**

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
2. Did you follow our generic troubleshooting steps already?
3. What Vanilla version are you using?
4. When did the issue start?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by charrondev** [comment]
You I could have sworn we had a bug filed for this, but apparently not, at least in this repo.

I'll say the team is aware of of some fundamental limitations in the notifications and activity.

What really makes this fundamentally difficult to fix is that the since the feature was added, is that rendered HTML of the notification/activity body is stored in the database.

This likely can't be fixed until we create a new activity table and structure, but it's such a massive task that affects relatively few communities.

There are also some other fundamental issues that make multi-lingual communities difficult that we are working on before this.

**Comment by Kaspar-K** [comment]
Thank you for the answer.

Ehm, did my description go?
I see the title I set but body-text of the issue have reverted to the standard pre-filled text 🤔

**Comment by charrondev** [comment]
I'm not sure. It actually was not there when I wrote my comment, but it is definitely a valid issue that I was aware of just by seeing the title. It doesn't look like it was edited either.

**Comment by Kaspar-K** [comment]
Still relevant
