### ISSUE TITLE
Enable image upload resizing by default

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#9048]
**Image Upload resizing should be enabled by default**

Vanilla now supports image resizing on upload but the feature is disabled by default. This is not useful. The feature should be enabled by default, at least on cloud. It creates a better user experience and results in a more affordable hosting scenario for the webmaster.

**User Story**

As a site host I would like to be able to leverage image resizing automatically, and disable it if I don't want it.

As a user I would like to download optimized images instead of the maximum possible resolution.

**Acceptance Criteria**

- Valid, sensible defaults for image resizing should be present in the config defaults
- Resizing/downsizing config should be true by default
- This should be enabled upon next utility/update so that it can be easily rolled out

**Comment by DaazKu** [comment]
I'm going to add my grain of salt here.

I don't think that turning the feature ON by default will solve the problem on Ops side. 
Currently we have one client taking 1/3rd of our total traffic. Having that client turn off the feature (because they can) will cause the same issue again.

Furthermore it will be hard to come up with a size that makes sense for everyone. Doing it on a per client basis would be a nightmare.

What would likely be a better solution would be to create a thumbnail of the big images and display that on the posts. If you click on the thumbnail you open the real image in a different window.
By doing so, opening a discussion with big images would not be  so costly bandwidth wise and it would allow users to see the full resolution images if they are really interested in doing so.

Optionally, as an example, we could say that 2500X2500 pixel is the limit (6.25Mpixel) size we allow for upload on our platform. This would ALWAYS be enforced not matter what. This would help to cut the number of edge cases (images of multiple MBs)
