### ISSUE TITLE
UserID in afterRegister event may be a string (REDIRECT_APPROVE constant)

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#9390]
`UserModel::validateSpamRegistration` may return the constant UserModel::REDIRECT_APPROVE instead of an ID:
https://github.com/vanilla/vanilla/blob/60fec99600beec2caf07908a88080485a0b6525e/applications/dashboard/models/class.usermodel.php#L3504

This is passed down all the way to the `afterRegister` event, where it is then passed as an event argument ("UserID").
https://github.com/vanilla/vanilla/blob/60fec99600beec2caf07908a88080485a0b6525e/applications/dashboard/models/class.usermodel.php#L2036

One might expect UserID to always be numeric, which in this case it is not.
This is confusing and undocumented, which leads me to believe, it is a bug.

Could there be plugins relying on this behaviour?
Otherwise I will supply a fix.

**Comment by charrondev** [comment]
@bleistivt after a quick look through our full codebase, including our proprietary plugins, the only references to this constant (or the value it represents) are in:

- `UserModel`
- `EntryController`
- `UsersApiController`

**Comment by charrondev** [comment]
I tracked down the commit where this was introduced https://github.com/vanilla/vanilla/commit/70b73e8c9eb0019bfe60d65ada9b973905d361a9

A string is definitely not appropriate because it may be cast to an int on a strongly typed method call, which would be an issue.

Maybe another constant to set as the userID which would be an int would work. Negative numbers tend to be used for this use case.
