### ISSUE TITLE
Refactor DateTimeFormatter::dateTimeToTimeStamp() RFC

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9489]
I noticed `DateTimermatter::dateTimeToTomeStamp()` triggering its warning in my output logs and found a few issues with the function. I think this function needs a bit of refactoring. I'm going to say what I think should be done and them my reasons why.

First, the function in question:

https://github.com/vanilla/vanilla/blob/50f75e3b87306a544ba93260140e27cf397e0ee5/library/Vanilla/Formatting/DateTimeFormatter.php#L223-L231

## Changes

1. The `$dateTime` parameter should not have a default. The default serves no purpose and leads to a warning anyway.
2. Just make the `$fallback` parameter the fallback. The caller can pass `time()` if they want that as the fallback.
3. Don't trigger a warning on fallback. Just return the fallback.
4. It's `Timestamp`, not `TimeStamp`.

Triggering a warning is at odds with the seeming purpose of this method, which is to cast a value into a timestamp or use the fallback I supplied. A warning on an expected output means that the programmer is going to have to do special handling. I would think the purpose of this method is to remove the need for special handling. Moreover, there are already other functions that also require special handling.

- I could use `strtotime()` and check against `false`.
- I could use the `DateTime` constructor and check for an exception.

In your case, I just want to return my fallback.

**Comment by charrondev** [comment]
I agree with you about the method signature. It ended up being used so broadly in the various other date time functions that were refactored that removing the fallback would have definitely caused fatal errors on some sites without adding a bunch of extra handling in 5-6 other functions. In retrospect that might have bee a better option.

I wasn't aware of how common useless or bad timestamps were in our sites due to migrations. Maybe it can be lowered to just be a notice instead of a warning? It essentially indicates dirty data. I actually saw an related migrations issue recently, but I can't find it. Maybe @patches knows what I'm talking about.

In any case changes can definitely be made.

**Comment by tburry** [comment]
If you want to keep the trigger I would think a notice is the right level. However, I would at least allow `null` or `''` to go to the default without any issue. You can have null dates in the database and those should not be an error.

**Comment by tburry** [comment]
@charrondev we had another case come up recently where this method could not be used because we needed to handle nullable timestamps. At this point I would like to just make a PR for the changes I want rather than going back and forth. Is that okay?
