### ISSUE TITLE
Session changing in UpdateModel breaks alt install method

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9655]
**Description**

On latest `master` it is not possible to install a new site because the session change introduced in https://github.com/vanilla/vanilla/pull/9498 can't be run on a site that's not installed yet.

**Current Status**

- Broken on `master`
- Changes revert on `release/2019.017` with https://github.com/vanilla/vanilla/pull/9653

**Why is it broken?**

- Installing a site use w/ the utility update based installation the infra uses fails with these changes.
- This is because we call `/utility/update` before writing into the config that the site is installed.
- `Gdn_Session::end()` fails when the site is not installed. 
- @DaazKu add some more details here please.
- Somehow this differs from the smoke test we use in our `AltTest` install method.

**Comment by DaazKu** [comment]
Ops install forums by calling `/utility/update.json` with `Garden.Installed` being `false`.

https://github.com/vanilla/vanilla/pull/9498 calls
`Gdn_Session->end()` which calls `$authenticator->authenticateWith()->deauthenticate();` which doesn't account for `Gdn_Auth->startAuthenticator()` returning  early because `Garden.Installed` is false.

**Comment by tburry** [comment]
I'm pretty sure this has been fixed.
